# -*- coding: utf-8 -*-
"""The committed styxx.v8 conformance set: it replays, it is addressed by its own bytes, and the
instrument that says so can fail.

Built to `styxx/v8/INTERFACES_layer2.md` section 10. Nothing here skips. A replay test that cannot
fail is a silent pass, so `TestTheInstrumentCanFail` breaks the set and the implementation on
purpose and asserts that the checks below notice -- without those, "every vector passes" would be a
sentence about the test file rather than about `styxx.v8`.

The set is data, and this file only ever reads it. It is regenerated by
`python conformance/v8/gen_vectors.py`, which refuses to write when a committed vector's outcome
has moved; a moved core is a finding about `styxx.v8` and belongs in a commit that says so.
"""
from __future__ import annotations

import base64
import copy
import hashlib
import json
from pathlib import Path

import pytest

from conformance.v8 import ENTRYPOINTS, FAMILIES, REASON_KINDS, SOURCES
from conformance.v8 import gen_vectors as G
from conformance.v8 import mutation_coverage as MC
from conformance.v8 import replay as R
from styxx.v8 import cert as certmod
from styxx.v8 import floor as floormod
from styxx.v8.jcs import canonical_bytes

SET_DIR = R.HERE
ROOT = R.ROOT

INDEX = R.load_index(SET_DIR)
BLOBS = R.load_blobs(SET_DIR)
VECTORS = R.load_vectors(SET_DIR)
ALL = [v for family in FAMILIES for v in VECTORS.get(family, [])]


# --------------------------------------------------------------------------- the set replays


class TestTheSetReplays:
    @pytest.mark.parametrize("family", FAMILIES)
    def test_every_vector_in_the_family_reproduces(self, family):
        """No skip, no tolerance: every vector's entrypoint returns what the vector expects."""
        vectors = VECTORS.get(family)
        assert vectors, f"the set carries no {family} family"
        failures = []
        for vector in vectors:
            why = R.check_vector(vector, BLOBS)
            if why is not None:
                failures.append("%s: %s" % (vector["id"], why))
        assert not failures, "%d of %d %s vectors do not reproduce:\n  %s" % (
            len(failures), len(vectors), family, "\n  ".join(failures[:10])
        )

    def test_the_whole_set_replays_and_nothing_is_left_out(self):
        counts, failures = R.replay_set(VECTORS, BLOBS)
        assert not failures
        replayed = sum(row["vectors"] for row in counts.values())
        assert replayed == len(ALL) == INDEX["vectors"], (
            "the index counts %d vectors, the family files hold %d, the replay saw %d"
            % (INDEX["vectors"], len(ALL), replayed)
        )

    def test_the_replay_calls_the_shipped_functions_not_a_recorder_wrapper(self):
        """Importing the recorder installs wrappers into `styxx.v8`; a replay must not use them."""
        assert certmod.check.__module__ == "styxx.v8.cert"
        assert floormod.decide.__module__ == "styxx.v8.floor"
        assert R.RUNNERS.keys() == ENTRYPOINTS.keys()


# --------------------------------------------------------------------------- addressing


class TestEveryVectorIsAddressedByItsOwnBytes:
    def test_the_id_is_the_hash_of_the_family_and_inputs(self):
        wrong = [
            v["id"] for v in ALL if v["id"] != R.vector_id(v["family"], v["inputs"])
        ]
        assert not wrong, "ids that are not the address of their own contents: %s" % wrong[:5]

    def test_ids_are_unique_and_each_family_file_is_sorted_by_id(self):
        assert len({v["id"] for v in ALL}) == len(ALL)
        for family, vectors in VECTORS.items():
            ids = [v["id"] for v in vectors]
            assert ids == sorted(ids), f"{family}.json is not sorted by id"

    def test_a_vector_sits_in_the_file_its_family_names(self):
        for family, vectors in VECTORS.items():
            for vector in vectors:
                assert vector["family"] == family
                assert ENTRYPOINTS[vector["entrypoint"]] == family

    def test_every_vector_names_the_tests_that_produced_it(self):
        for vector in ALL:
            sources = vector["sources"]
            assert sources and sources == sorted(set(sources))
            for source in sources:
                assert source.split("::")[0] in SOURCES, source


class TestTheBlobStore:
    def test_every_blob_hashes_to_its_key(self):
        for sha, payload in BLOBS.items():
            raw = base64.b64decode(payload, validate=True)
            assert hashlib.sha256(raw).hexdigest() == sha

    def test_every_blob_is_canonical_json_that_round_trips(self):
        for sha in BLOBS:
            raw = R.blob_bytes(BLOBS, sha)
            assert canonical_bytes(json.loads(raw.decode("utf-8"))) == raw

    def test_the_store_carries_exactly_what_the_vectors_name(self):
        named = set()
        for vector in ALL:
            named |= R.blob_refs(vector)
        missing = named - set(BLOBS)
        assert not missing, "vectors name blobs the store does not carry: %s" % sorted(missing)[:5]
        orphans = set(BLOBS) - named
        assert not orphans, "the store carries blobs nothing names: %s" % sorted(orphans)[:5]

    def test_the_result_body_a_diff_digests_is_carried_so_a_move_can_be_diffed(self):
        """`exit` vectors pin a hash; the bytes behind it are in the store, not only the hash."""
        outcomes = [v for v in VECTORS["exit"] if "result_sha256" in v["expect"]]
        assert outcomes
        for vector in outcomes:
            body = R.blob_value(BLOBS, vector["expect"]["result_sha256"])
            assert body["kind"] == "verify"
            assert body["overall"] == vector["expect"]["verdict"]


# --------------------------------------------------------------------------- the index


class TestTheIndex:
    def test_set_sha256_is_over_the_index_without_itself_or_its_provenance(self):
        core = {k: v for k, v in INDEX.items() if k not in ("set_sha256", "provenance")}
        assert hashlib.sha256(canonical_bytes(core)).hexdigest() == INDEX["set_sha256"]

    @pytest.mark.parametrize("family", FAMILIES)
    def test_each_family_file_hashes_to_what_the_index_says(self, family):
        row = INDEX["families"][family]
        data = (SET_DIR / row["file"]).read_bytes()
        assert hashlib.sha256(data).hexdigest() == row["sha256"]
        assert row["count"] == len(VECTORS[family])

    def test_the_blob_store_hashes_to_what_the_index_says(self):
        data = (SET_DIR / INDEX["blobs"]["file"]).read_bytes()
        assert hashlib.sha256(data).hexdigest() == INDEX["blobs"]["sha256"]
        assert INDEX["blobs"]["count"] == len(BLOBS)

    def test_the_index_counts_the_vectors_each_entrypoint_produced(self):
        counted = {name: 0 for name in ENTRYPOINTS}
        for vector in ALL:
            counted[vector["entrypoint"]] += 1
        for name, row in INDEX["entrypoints"].items():
            assert row["vectors"] == counted[name], name
            assert row["family"] == ENTRYPOINTS[name]

    def test_the_sources_are_the_ones_the_contract_names(self):
        assert tuple(INDEX["sources"]) == SOURCES
        for path in SOURCES:
            assert (ROOT / path).is_file()


class TestTheHonestRemainder:
    """`index.unvectored` is what the set does not reach. A gap is named, never inferred."""

    def test_every_reason_kind_is_either_reached_or_listed(self):
        reached = set()
        for vector in VECTORS["cert"]:
            reached |= set(vector["expect"].get("reason_kinds") or [])
        listed = set(INDEX["unvectored"]["reason_kinds"])
        assert reached & listed == set(), "a kind cannot be both reached and unvectored"
        assert reached | listed == set(REASON_KINDS)

    def test_every_channel_verdict_is_either_reached_or_listed(self):
        reached = {v["expect"]["verdict"] for v in VECTORS["decide"]
                   if v["expect"]["outcome"] == "verdict"}
        listed = set(INDEX["unvectored"]["channel_verdicts"])
        assert reached & listed == set()
        assert reached | listed == set(floormod.CHANNEL_VERDICTS)

    def test_every_gap_carries_a_note_that_says_why(self):
        notes = INDEX["unvectored"]["notes"]
        gaps = []
        for kind, key in (("reason_kind", "reason_kinds"), ("exit_code", "exit_codes"),
                          ("channel_verdict", "channel_verdicts"), ("entrypoint", "entrypoints")):
            gaps += ["%s:%s" % (kind, item) for item in INDEX["unvectored"][key]]
        assert sorted(notes) == sorted(gaps)
        unexplained = [k for k, v in notes.items() if v == "no note: an unexplained gap"]
        assert not unexplained, "a gap with no account of why: %s" % unexplained

    def test_every_skipped_call_says_which_test_made_it_and_why(self):
        rows = INDEX["unvectored"]["skipped"] + INDEX["unvectored"]["sources"]
        assert rows, "the set claims to have carried every call it saw"
        for row in rows:
            assert row["source"].split("::")[0] in SOURCES
            assert row["reason"]

    def test_the_property_tests_are_named_and_none_of_them_produced_a_vector(self):
        property_tests = {row["source"] for row in INDEX["unvectored"]["sources"]}
        assert property_tests
        produced = {source for vector in ALL for source in vector["sources"]}
        assert property_tests & produced == set()


# --------------------------------------------------------------------------- the calibration


CATALOGUE = json.loads((SET_DIR / "mutation_catalogue.json").read_text(encoding="utf-8"))
MUTATIONS = CATALOGUE["mutations"]
COVERAGE = json.loads((SET_DIR / "mutation_coverage.json").read_text(encoding="utf-8"))


class TestTheMutationCatalogue:
    """The lab's rule: an agreement number ships with a measurement of its detection power."""

    def test_the_catalogue_has_the_semantic_mutations_and_the_controls_the_contract_asks_for(self):
        semantic = [m for m in MUTATIONS if not m["control"]]
        controls = [m for m in MUTATIONS if m["control"]]
        assert len(semantic) >= 12
        assert len(controls) >= 3

    def test_names_are_unique_and_every_mutation_says_what_it_breaks(self):
        names = [m["name"] for m in MUTATIONS]
        assert len(set(names)) == len(names)
        for mutation in MUTATIONS:
            assert mutation["why"].strip()
            assert mutation["region"].strip()
            assert mutation["old"] != mutation["new"]

    @pytest.mark.parametrize("mutation", MUTATIONS, ids=[m["name"] for m in MUTATIONS])
    def test_the_anchor_names_exactly_one_place_in_a_mutable_module(self, mutation):
        assert mutation["module"] in MC.MUTABLE
        source = MC._source(mutation["module"])
        assert source.count(mutation["old"]) == 1, (
            "%s: the anchor occurs %d times; an edit must name one place"
            % (mutation["name"], source.count(mutation["old"]))
        )


class TestTheMutationCoverage:
    def test_the_receipt_measures_the_committed_set_and_this_catalogue(self):
        assert COVERAGE["set"]["set_sha256"] == INDEX["set_sha256"], (
            "the coverage receipt was measured against a different set; rerun "
            "conformance/v8/mutation_coverage.py"
        )
        digest = hashlib.sha256(
            (SET_DIR / "mutation_catalogue.json").read_bytes().replace(b"\r\n", b"\n")
        ).hexdigest()
        assert COVERAGE["catalogue"]["sha256"] == digest

    def test_the_receipt_measures_the_modules_in_the_tree_today(self):
        for rel, sha in COVERAGE["implementation"].items():
            assert MC._sha(rel) == sha, (
                "%s has changed since the coverage run; the receipt no longer describes this "
                "tree, and a receipt is history -- rerun the measurement into a new file" % rel
            )

    def test_no_control_was_caught(self):
        """A caught control voids the run: the set would be detecting editing, not behaviour."""
        assert COVERAGE["counts"]["controls_caught"] == 0
        assert COVERAGE["void"] is False

    def test_the_gates_that_can_be_passed_are_passed(self):
        for name in ("G-M", "G-C", "G-K", "G-R"):
            assert COVERAGE["gates"][name]["pass"] is True, name
        assert COVERAGE["gates"]["G-D"]["pass"] is None, (
            "a detection rate is reported, never passed or failed"
        )

    def test_the_arithmetic_of_the_run_holds(self):
        counts = COVERAGE["counts"]
        assert counts["caught"] + counts["missed"] == counts["viable"]
        assert counts["proposed"] == len(MUTATIONS)
        assert counts["viable"] + counts["controls_viable"] + counts["anchor_missing"] \
            + counts["anchor_ambiguous"] + counts["non_viable"] + counts["no_op"] \
            + counts["not_mutable"] == counts["proposed"]

    def test_the_miss_list_is_carried_in_full_and_every_miss_says_why(self):
        missed = COVERAGE["missed"]
        assert len(missed) == COVERAGE["counts"]["missed"]
        catalogued = {m["name"]: m for m in MUTATIONS}
        for row in missed:
            assert row["name"] in catalogued
            assert row["why"] == catalogued[row["name"]]["why"]
            assert row["why"].strip()

    def test_a_caught_mutation_names_the_vector_that_noticed(self):
        caught = [m for m in COVERAGE["mutations"] if m["verdict"] == "caught"]
        assert caught
        by_id = {v["id"]: v for v in ALL}
        for row in caught:
            assert row["noticed"] > 0
            assert row["example"]["id"] in by_id


# --------------------------------------------------------------------------- the instrument


class TestTheInstrumentCanFail:
    """Without this class the rest of the file is a sentence about itself.

    Each test breaks one thing on purpose and asserts the corresponding check reports it. Nothing
    on disk is touched: the set is copied in memory and the implementation is restored in a
    `finally`.
    """

    def test_a_vector_whose_expect_is_wrong_is_reported(self):
        vector = copy.deepcopy(VECTORS["decide"][0])
        vector["expect"] = {"outcome": "verdict", "verdict": "not-a-verdict"}
        why = R.check_vector(vector, BLOBS)
        assert why is not None and "verdict" in why

    def test_a_vector_whose_id_is_not_its_address_is_reported(self):
        vector = copy.deepcopy(VECTORS["merkle"][0])
        vector["id"] = "0" * 64
        why = R.check_vector(vector, BLOBS)
        assert why is not None and "is not the address" in why

    def test_a_blob_that_does_not_hash_to_its_key_is_refused(self):
        vector = VECTORS["cert"][0]
        sha = vector["inputs"]["cert"]
        tampered = dict(BLOBS)
        tampered[sha] = base64.b64encode(b'{"tampered":true}').decode("ascii")
        with pytest.raises(R.ReplayError) as excinfo:
            R.check_vector(vector, tampered)
        assert "hashes to" in str(excinfo.value)

    def test_a_missing_blob_is_refused_rather_than_passed_over(self):
        vector = VECTORS["cert"][0]
        short = {k: v for k, v in BLOBS.items() if k != vector["inputs"]["cert"]}
        with pytest.raises(R.ReplayError) as excinfo:
            R.check_vector(vector, short)
        assert "does not carry" in str(excinfo.value)

    def test_an_implementation_that_changes_its_answer_is_caught_by_the_replay(self):
        """The replay reaches `styxx.v8`, not a copy of the expectations."""
        real = floormod.decide
        floormod.decide = lambda *a, **k: "same"
        try:
            _counts, failures = R.replay_set({"decide": VECTORS["decide"]}, BLOBS)
        finally:
            floormod.decide = real
        assert failures, "every decide vector agreed with a function that always says `same`"

    def test_the_mutation_harness_installs_and_restores_a_module(self):
        """`install`/`uninstall` are what every coverage number rests on."""
        import sys
        rel = "styxx/v8/floor.py"
        source = MC._source(rel).replace('        return "exceeds_floor"', '        return "drift"')
        assert 'return "drift"' in source
        import tempfile
        with tempfile.TemporaryDirectory() as td:
            mutant = MC.load_mutant(rel, source, Path(td))
            undo = MC.install(rel, mutant)
            try:
                assert sys.modules["styxx.v8.floor"] is mutant
                _counts, failures = R.replay_set({"decide": VECTORS["decide"]}, BLOBS)
            finally:
                MC.uninstall(undo)
        assert failures, "a decide vector should have noticed exceeds_floor becoming drift"
        assert sys.modules["styxx.v8.floor"] is floormod
        assert R.floormod is floormod
        _counts, failures = R.replay_set({"decide": VECTORS["decide"]}, BLOBS)
        assert not failures, "uninstall did not put the real module back"


class TestTheGeneratorRefusesRatherThanRewrites:
    """The two refusals that keep a receipt from being edited into agreement."""

    DECIDE = {
        "family": "decide",
        "entrypoint": "floor.decide",
        "inputs": {"distance": 0, "floor": 0, "confirmation": None,
                   "covered": True, "skew": False},
        "blobs": {},
    }

    def test_one_address_carrying_two_outcomes_is_refused(self):
        """The guard that caught a real defect: `verify.diff` once recorded a `None` resolver and
        a refused resolver as the same inputs, and the same id then carried two outcomes."""
        first = dict(self.DECIDE, source="t.py::a",
                     expect={"outcome": "verdict", "verdict": "same"})
        second = dict(self.DECIDE, source="t.py::b",
                      expect={"outcome": "verdict", "verdict": "drift"})
        with pytest.raises(SystemExit) as excinfo:
            G.fold([first, second])
        assert "two outcomes" in str(excinfo.value)

    def test_one_call_recorded_from_two_tests_becomes_one_vector_naming_both(self):
        expect = {"outcome": "verdict", "verdict": "same"}
        vectors, _blobs, _skipped, _sources = G.fold([
            dict(self.DECIDE, source="t.py::b", expect=expect),
            dict(self.DECIDE, source="t.py::a", expect=expect),
        ])
        assert len(vectors) == 1
        assert next(iter(vectors.values()))["sources"] == ["t.py::a", "t.py::b"]

    def test_a_committed_vector_whose_outcome_moved_is_reported_by_id(self):
        old = {v["id"]: v for v in VECTORS["decide"][:3]}
        new = copy.deepcopy(old)
        victim = sorted(new)[0]
        new[victim]["expect"] = {"outcome": "verdict", "verdict": "not-what-it-was"}
        moved = G.compare_to_committed(old, new)
        assert len(moved) == 1 and victim in moved[0]

    def test_adding_and_dropping_a_vector_are_not_moved_cores(self):
        old = {v["id"]: v for v in VECTORS["decide"][:3]}
        new = {v["id"]: v for v in VECTORS["decide"][1:4]}
        assert G.compare_to_committed(old, new) == []

    def test_a_drop_that_still_reproduces_and_one_that_does_not_are_told_apart(self):
        """The diagnostic the refusal now rests on: "dropped" is one word for two events."""
        churn = copy.deepcopy(VECTORS["cert"][0])
        moved = copy.deepcopy(VECTORS["cert"][1])
        moved["expect"] = dict(moved["expect"], ok=not moved["expect"]["ok"])
        old = {churn["id"]: churn, moved["id"]: moved}
        rows = {r["id"]: r for r in G.classify_drops(old, {}, BLOBS)}
        assert rows[churn["id"]]["kind"] == "input-churn"
        assert rows[moved["id"]]["kind"] == "behaviour-change"
        assert rows[moved["id"]]["now"] != rows[moved["id"]]["was"]
        assert rows[churn["id"]]["detail"] and rows[moved["id"]]["detail"]

    def test_a_drop_that_cannot_be_replayed_is_undiagnosed_rather_than_assumed_benign(self):
        vector = copy.deepcopy(VECTORS["cert"][0])
        rows = G.classify_drops({vector["id"]: vector}, {}, {})
        assert rows[0]["kind"] == "undiagnosed"
        assert "cannot be replayed" in rows[0]["detail"]

    def test_the_skipped_calls_are_folded_out_of_the_vectors_and_into_the_remainder(self):
        vectors, _blobs, skipped, sources = G.fold([
            {"source": "t.py::a", "entrypoint": "cert.check", "skip": "holds a NaN"},
            {"source": "t.py::h", "entrypoint": "*", "skip": "a property test"},
        ])
        assert vectors == {}
        assert [r["reason"] for r in skipped] == ["holds a NaN"]
        assert [r["source"] for r in sources] == ["t.py::h"]


class TestRetiringAMovedCoreTakesAReason:
    """The third option in `papers/v8/FINDING_moved_cores_2026_09_09.md`, built so it cannot
    become an override: the ids are named, the reasons are required, and an ordinary retirement
    cannot be laundered through the path."""

    MOVED = {"id": "a" * 64, "kind": "moved-core", "entrypoint": "cert.check",
             "was": {"ok": True}, "now": {"ok": False}, "sources": ["tests/t.py::x"]}
    DRIFTED = {"id": "b" * 64, "kind": "behaviour-change", "entrypoint": "cert.check",
               "was": {"ok": True}, "now": {"ok": False}, "sources": ["tests/t.py::y"],
               "detail": "ok: expected true, replayed false"}
    CHURNED = {"id": "c" * 64, "kind": "input-churn", "entrypoint": "cert.check",
               "was": {"ok": True}, "now": {"ok": True}, "sources": ["tests/t.py::z"],
               "detail": "it still reproduces"}

    def test_an_id_with_no_reason_is_refused(self):
        with pytest.raises(SystemExit) as excinfo:
            G.retirement_plan([self.MOVED["id"]], [])
        assert "positional pairs" in str(excinfo.value)
        with pytest.raises(SystemExit) as excinfo:
            G.retirement_plan([self.MOVED["id"]], ["   "])
        assert "empty reason" in str(excinfo.value)

    def test_one_address_cannot_be_retired_twice_with_two_reasons(self):
        with pytest.raises(SystemExit) as excinfo:
            G.retirement_plan([self.MOVED["id"]] * 2, ["one", "another"])
        assert "given twice" in str(excinfo.value)

    def test_a_moved_core_nobody_named_is_still_a_refusal(self):
        """There is no flag that retires whatever moved; silence is the default refusal."""
        _rec, unnamed, refusals = G.apply_retirements({}, [self.MOVED], [self.DRIFTED])
        assert unnamed == sorted([self.MOVED["id"], self.DRIFTED["id"]])
        assert refusals == []

    def test_an_ordinary_retirement_cannot_be_laundered_through_the_path(self):
        plan = G.retirement_plan([self.CHURNED["id"]], ["it looked untidy"])
        _rec, _unnamed, refusals = G.apply_retirements(plan, [], [self.CHURNED])
        assert len(refusals) == 1 and "still reproduces" in refusals[0]

    def test_an_address_that_did_not_move_cannot_be_retired(self):
        plan = G.retirement_plan(["d" * 64], ["pre-emptive"])
        _rec, _unnamed, refusals = G.apply_retirements(plan, [self.MOVED], [])
        assert len(refusals) == 1 and "did not move in this run" in refusals[0]

    def test_a_named_address_is_recorded_with_its_reason_and_both_outcomes(self):
        plan = G.retirement_plan(
            [self.MOVED["id"], self.DRIFTED["id"]], ["ENV-ABSENT closed it", "A-NORUNS closed it"]
        )
        recorded, unnamed, refusals = G.apply_retirements(plan, [self.MOVED], [self.DRIFTED])
        assert (unnamed, refusals) == ([], [])
        by_id = {row["id"]: row for row in recorded}
        assert by_id[self.MOVED["id"]]["reason"] == "ENV-ABSENT closed it"
        assert by_id[self.MOVED["id"]]["kind"] == "moved-core"
        assert by_id[self.DRIFTED["id"]]["kind"] == "behaviour-change"
        for row in recorded:
            assert row["was"] != row["now"]
            assert row["sources"]

    def test_the_ledger_carries_forward_and_does_not_record_one_move_twice(self):
        plan = G.retirement_plan([self.MOVED["id"]], ["because"])
        recorded, _unnamed, _refusals = G.apply_retirements(plan, [self.MOVED], [])
        first = G.retirement_ledger({}, recorded, [self.CHURNED], current=set())
        again = G.retirement_ledger(first, recorded, [self.CHURNED], current=set())
        assert [r["id"] for r in first["with_reason"]] == [self.MOVED["id"]]
        assert [r["id"] for r in again["with_reason"]] == [self.MOVED["id"]]
        assert [r["id"] for r in again["input_churn"]] == [self.CHURNED["id"]]

    def test_an_address_the_sources_produce_again_leaves_the_churn_ledger(self):
        previous = G.retirement_ledger({}, [], [self.CHURNED], current=set())
        back = G.retirement_ledger(previous, [], [], current={self.CHURNED["id"]})
        assert back["input_churn"] == []

    def test_the_two_kinds_of_retirement_are_different_rows_in_the_committed_set(self):
        """A reader diffing the set sees which retirements were decided and which just happened."""
        retired = INDEX["provenance"]["retired"]
        assert retired["note"].strip()
        assert retired["with_reason"], "the set records no retirement with a reason"
        ids = {v["id"] for v in ALL}
        for row in retired["with_reason"]:
            assert row["reason"].strip()
            assert row["was"] != row["now"]
            assert row["kind"] in ("moved-core", "behaviour-change", "undiagnosed")
            assert row["sources"]
            assert (row["id"] in ids) == (row["kind"] == "moved-core")
        for row in retired["input_churn"]:
            assert set(row) == {"id", "entrypoint"}, "an ordinary retirement carries no reason"
            assert row["id"] not in ids
        assert not ({r["id"] for r in retired["with_reason"]}
                    & {r["id"] for r in retired["input_churn"]})


# --------------------------------------------------------------------------- the README


class TestTheREADME:
    README = (SET_DIR / "README.md").read_text(encoding="utf-8")

    def test_it_names_every_file_the_set_ships(self):
        for name in ("index.json", "blobs.json", "recorder.py", "gen_vectors.py", "replay.py",
                     "mutation_catalogue.json", "mutation_coverage.py", "mutation_coverage.json"):
            assert name in self.README, name

    def test_it_does_not_write_a_count_that_belongs_in_the_receipts(self):
        """The lab's style: the numbers live in `index.json` and `mutation_coverage.json`."""
        for number in (str(len(ALL)), str(len(BLOBS)), str(COVERAGE["counts"]["caught"]),
                       str(COVERAGE["gates"]["G-D"]["value"]["rate"])):
            assert number not in self.README, "the README writes a count: %s" % number
