#!/usr/bin/env python3
"""build_sand_survey.py — the record behind SURVEY_sand_neighbours_2026_09_13.md.

    python papers/plates/build_sand_survey.py <fetch_record.json>   # writes papers/plates/sand_prior_art_survey.json

The verdicts below were entered by the surveyor after reading each source on 2026-09-13 under
PROTOCOL_sand_prior_art_2026_09_13.md (committed before any fetch, 9f5fd42c). The fetch record
(url as fetched, effective url, http status, bytes, sha256, fetch time; for papers also the full-text
PDF's bytes and sha256) is merged in from the file the fetch wrote. Status READ means the whole page or
paper was processed end to end; SKIMMED means the pages named were read and the rest were not, so the
source may only OCCUPY or be SILENT, never RETIRE; UNFETCHABLE means the bytes fetched carry no content
to read (the archived Proof of Existence page is a script shell whose text is its title).
"""
import json
import sys

fetch = json.load(open(sys.argv[1], encoding="utf-8"))

SOURCES = {
 "S01": dict(title="Hash Visualization: a New Technique to Improve Real-World Security", who="Perrig & Song", year=1999, status="SKIMMED", pages_read="1-6 of the PDF",
             verdicts={"C3": ("OCCUPIES", "public-key fingerprints and root keys, compared by eye", "The visual fingerprints generated by Random Art are clearly easier to compare than the hexadecimal representation.")}),
 "S02": dict(title="OpenSSH 5.1 release notes", who="OpenSSH project", year=2008, status="READ", pages_read="whole document",
             verdicts={"C3": ("OCCUPIES", "SSH host keys", "render SSH host keys in a visual form that is amenable to easy recall and rejection of changed host keys")}),
 "S03": dict(title="Visual Security: 9-block IP Identification (the post that named identicons)", who="Don Park", year=2007, status="READ", pages_read="whole post, archived copy of 2007-12-15",
             verdicts={"C3": ("OCCUPIES", "a commenter's hashed IP address", "using a privacy protecting derivative of each commenter's IP address to build a 9-block image")}),
 "S04": dict(title="How To Time-Stamp a Digital Document", who="Haber & Stornetta", year=1991, status="SKIMMED", pages_read="1-3 of 13",
             verdicts={"C4b": ("OCCUPIES", "any digital document, through a time-stamping service (from the pages read; the linking scheme in later sections was not read)", "We propose computationally practical procedures for digital time-stamping of such documents so that it is infeasible for a user either to back-date or to forward-date his document")}),
 "S05": dict(title="OpenTimestamps: A timestamping proof standard", who="Peter Todd / OpenTimestamps", year=2016, status="READ", pages_read="whole page",
             verdicts={"C4b": ("RETIRES", "any data, anchored to the Bitcoin blockchain, independently verifiable — a preregistration is data", "A timestamp proves that some data existed prior to some point in time. OpenTimestamps defines a set of operations for creating provable timestamps and later independently verifying them.")}),
 "S06": dict(title="Proof of Existence", who="Manuel Araoz", year=2013, status="UNFETCHABLE", pages_read="the archived page carries only its title; the application is a script shell",
             verdicts={"C4b": ("UNCHECKABLE", "", "")}),
 "S07": dict(title="Certificate Transparency, RFC 6962", who="Laurie, Langley & Kasper", year=2013, status="READ", pages_read="whole document",
             verdicts={"C2": ("OCCUPIES", "certificates in an append-only Merkle log with a signed tree head, checked by monitors — the same mechanism for a different object", "The append-only property of each log is technically achieved using Merkle Trees, which can be used to show that any particular version of the log is a superset of any previous version.")}),
 "S08": dict(title="Rekor (Sigstore transparency log), overview", who="Sigstore project", year=2021, status="READ", pages_read="whole page",
             verdicts={"C2": ("OCCUPIES", "signed supply-chain metadata in an append-only ledger audited for consistency", "Rekor aims to provide an immutable, tamper-resistant ledger of metadata generated within a software project's supply chain.")}),
 "S09": dict(title="The past, present and future of Registered Reports", who="Chambers & Tzavella", year=2022, status="SKIMMED", pages_read="abstract only; the article is paywalled",
             verdicts={"C4b": ("OCCUPIES", "a journal's in-principle acceptance of a protocol before the work, not a public-ledger hash (from abstract)", "study proposals are peer reviewed and pre-accepted before research is undertaken")}),
 "S10": dict(title="Preregistration (Center for Open Science programme page)", who="Center for Open Science", year=2026, status="READ", pages_read="whole page",
             verdicts={"C4b": ("OCCUPIES", "a timestamped registration on OSF", "specifying your research plan in advance of your study and submitting it to a registry"),
                       "C5": ("OCCUPIES", "a prize for publishing preregistered work; the campaign ended in 2018 and paid for preregistering, not for breaking a verifier", "The campaign included $1000 prizes for researchers who published the results of preregistered work.")}),
 "S11": dict(title="How Is ChatGPT's Behavior Changing over Time?", who="Chen, Zaharia & Zou", year=2023, status="SKIMMED", pages_read="1-6 of the PDF",
             verdicts={"C4a": ("OCCUPIES", "an API service's task accuracy and per-prompt answer mismatch across versions; no log-prob fingerprint, no same-weights floor", "how often, for the same prompt, the extracted answers by two versions of the same LLM service do not match")}),
 "S12": dict(title="Accuracy is Not All You Need", who="Dutta, Krishnan, Kwatra & Ramjee", year=2024, status="SKIMMED", pages_read="1-6 of the PDF",
             verdicts={"C4a": ("OCCUPIES", "compressed versus baseline models by KL divergence over token distributions and per-item flips on benchmark sets; no hashed canary set, no in-situ same-weights floor, no verdict with an interval — the nearest neighbour of the checksum's measurement", "We propose two such metrics, KL-Divergence and % flips, and show that they are well correlated.")}),
 "S13": dict(title="Instructional Fingerprinting of Large Language Models", who="Xu et al.", year=2024, status="SKIMMED", pages_read="1-4 of the PDF",
             verdicts={"C4a": ("OCCUPIES", "an ownership fingerprint implanted by fine-tuning and verified by its trigger", "the model publisher specifies a confidential private key and implants it as an instruction backdoor")}),
 "S14": dict(title="REEF: Representation Encoding Fingerprints for Large Language Models", who="Zhang et al.", year=2024, status="SKIMMED", pages_read="1-4 of the PDF",
             verdicts={"C4a": ("OCCUPIES", "centered-kernel-alignment similarity of two models' representations on the same samples, to decide derivation — a neighbour of the belief-geometry agreement", "REEF computes and compares the centered kernel alignment similarity between the representations of a suspect model and a victim model on the same samples.")}),
 "S15": dict(title="Representational similarity analysis - connecting the branches of systems neuroscience", who="Kriegeskorte, Mur & Bandettini", year=2008, status="READ", pages_read="whole article",
             verdicts={"C4a": ("OCCUPIES", "representational dissimilarity matrices compared across systems by correlation of their upper triangles, with a noise floor — the rdm_r half of the fingerprint, for brains", "RDMs can be quantitatively compared using correlation distance (1-correlation) or rank-correlation distance.")}),
 "S16": dict(title="Defeating Nondeterminism in LLM Inference", who="Horace He and Thinking Machines Lab", year=2025, status="READ", pages_read="whole post",
             verdicts={"C4a": ("OCCUPIES", "the same-weights spread of served completions under identical requests — a null floor measured on completions, not a fingerprint distance graded against it", "we generate 80 unique completions, with the most common of these occuring 78 times")}),
 "S17": dict(title="A Sober Look at Progress in Language Model Reasoning: Pitfalls and Paths to Reproducibility", who="Hochlehnert et al.", year=2025, status="READ", pages_read="whole paper via the fetch; pages 1-5 also read directly",
             verdicts={"C4a": ("OCCUPIES", "seed and hardware variance of aggregate benchmark scores under the same weights — a floor at the score level, not per item", "Pass@1 values show surprisingly high standard deviation - ranging from 5 to 15 percentage points across seeds.")}),
 "S18": dict(title="Improving Reproducibility in Machine Learning Research (A Report from the NeurIPS 2019 Reproducibility Program)", who="Pineau et al.", year=2021, status="SKIMMED", pages_read="1-6 of the PDF",
             verdicts={"C5": ("OCCUPIES", "a community challenge to reproduce accepted papers, with recognition rather than a standing payment against a verifier (from the pages read)", "a community-wide reproducibility challenge")}),
 "S19": dict(title="Proof-of-Learning: Definitions and Practice", who="Jia et al.", year=2021, status="SKIMMED", pages_read="1-5 of the PDF",
             verdicts={"C4a": ("SILENT", "training provenance, not served behavior", ""),
                       "C4b": ("OCCUPIES", "a proof of training, or its signature, published to a public ledger", "The proof (or its signature) can be timestamped, or published in a public ledger.")}),
 "S20": dict(title="Bug Bounty Programs (Immunefi)", who="Immunefi", year=2026, status="READ", pages_read="whole page",
             verdicts={"C5": ("OCCUPIES", "standing bounties for security vulnerabilities in deployed code, adjudicated by Immunefi — a standing payment against a verifier of code, not of a lab's own claims", "Find bugs. Get paid. ... Triaged by Immunefi")}),
}

CLAUSES = {
 "C1": "binds every published number to bytes at a commit",
 "C2": "re-derives every verdict from those bytes into a chained log",
 "C3": "gives every receipt a face a stranger reads without json",
 "C4a": "fingerprints a model's behavior on hashed canaries against a measured null floor",
 "C4b": "under a preregistration sealed on a public chain before the run",
 "C5": "pays a standing bounty against its own verifier",
}
NEAREST = {"C2": ["S07", "S08"], "C3": ["S01", "S02"], "C4a": ["S12", "S16"], "C4b": ["S05", "S04"], "C5": ["S20", "S10"]}

LEADS = [
 "ChatLog (Tu et al., 2023): recording and monitoring ChatGPT responses over time — cited by S11",
 "CKA (Kornblith et al., 2019): the similarity index REEF builds on — cited by S14",
 "a longitudinal dataset of commercial ML-service responses (cited by S11 as CJE+22)",
 "Kanare, a similar time-stamping proposal cited by S04 as recently learned of",
 "Gromov et al. (2024): dropping layers without accuracy loss, where S12 finds flips rising",
 "Sigstore's transparency-log background page, linked from S08 and not on the list",
]

sources = {}
for sid, s in SOURCES.items():
    f = fetch[sid]
    rec = {"title": s["title"], "who": s["who"], "year": s["year"], "status": s["status"], "pages_read": s["pages_read"],
           "url": f["url"], "url_effective": f["url_effective"], "http": f["http"], "bytes": f["bytes"], "sha256": f["sha256"],
           "fetched_at": f["fetched_at"], "verdicts": {}}
    if "fulltext_pdf" in f:
        rec["fulltext_pdf_sha256"] = f["fulltext_pdf"]["sha256"]
        rec["fulltext_pdf_bytes"] = f["fulltext_pdf"]["bytes"]
    for cid, (v, obj, quote) in s["verdicts"].items():
        rec["verdicts"][cid] = {"verdict": v, "object": obj, "quote": quote}
    sources[sid] = rec

clauses = {"C1": {"clause": CLAUSES["C1"], "status": "OCCUPIED", "inherited_from": "papers/sworn/SURVEY_sworn_neighbours_2026_09_05.md",
                  "retired_by": [], "occupied_by": [], "nearest": []}}
for cid in ("C2", "C3", "C4a", "C4b", "C5"):
    retired, occupied, unfetchable = [], [], []
    for sid, rec in sources.items():
        v = rec["verdicts"].get(cid)
        if not v:
            continue
        if v["verdict"] == "RETIRES" and rec["status"] == "READ":
            retired.append(sid)
        elif v["verdict"] in ("OCCUPIES", "RETIRES"):
            occupied.append(sid)      # a RETIRES from a SKIMMED source counts as OCCUPIES; none was entered
        elif v["verdict"] == "UNCHECKABLE":
            unfetchable.append(sid)
    status = "RETIRED" if retired else ("UNPRICED" if unfetchable else ("OCCUPIED" if occupied else "FREE"))
    clauses[cid] = {"clause": CLAUSES[cid], "status": status, "retired_by": retired, "occupied_by": occupied,
                    "unfetchable_candidates": unfetchable, "nearest": NEAREST[cid]}

# the conjunction: retired only if one READ source retires or occupies C2..C5 at once; else the weakest status
order = ["RETIRED", "UNPRICED", "OCCUPIED", "FREE"]
one_source_all = [sid for sid, rec in sources.items() if rec["status"] == "READ" and all(
    rec["verdicts"].get(c, {}).get("verdict") in ("OCCUPIES", "RETIRES") for c in ("C2", "C3", "C4a", "C4b", "C5"))]
statuses = [clauses[c]["status"] for c in ("C1", "C2", "C3", "C4a", "C4b", "C5")]
weakest = min(statuses, key=order.index)
conj_status = "RETIRED" if one_source_all else weakest
surviving = [c for c in ("C1", "C2", "C3", "C4a", "C5") if clauses[c]["status"] == "OCCUPIED"]
deleted = [c for c in ("C1", "C2", "C3", "C4a", "C4b", "C5") if clauses[c]["status"] in ("RETIRED", "UNPRICED")]
fatal = any(clauses[c]["status"] == "RETIRED" for c in ("C4a", "C5"))

SENTENCE = ("We know of no lab that binds every published number to bytes at a commit (where sworn's neighbours bind "
            "numerals, artifacts and structured assertions, as the 2026-09-05 survey names them), re-derives every verdict "
            "from those bytes into a chained log (where Certificate Transparency and Rekor chain certificates and signed "
            "metadata, not verdicts), gives every receipt a face a stranger reads without json (where random art gives "
            "a host key one and an identicon gives an address one), fingerprints a model's behavior on hashed canaries "
            "against a measured null floor (where Dutta et al. measure flips and KL divergence under compression, and "
            "Thinking Machines measure the same-weights spread of served completions), and pays a standing bounty against "
            "its own verifier (where Immunefi pays against deployed code and the Preregistration Challenge paid for "
            "preregistering) — at once. The seal on a public chain is not in this sentence: OpenTimestamps does that for "
            "any document, and has since 2016.")

out = {
 "survey": "the sand: the neighbours of one sentence",
 "protocol": "papers/plates/PROTOCOL_sand_prior_art_2026_09_13.md",
 "protocol_commit": "9f5fd42c",
 "run_by": "one agent, one pass, on the lab's second machine; page sources read through a fetch-and-summarise tool with the whole page as input, papers read from their bytes page by page; no independent re-fetch",
 "run_date": "2026-09-13",
 "status": "COMPLETE",
 "counts": {"sources_in_list": len(sources), "sources_scored": len(sources),
            "read": sum(1 for r in sources.values() if r["status"] == "READ"),
            "skimmed": sum(1 for r in sources.values() if r["status"] == "SKIMMED"),
            "unfetchable": sum(1 for r in sources.values() if r["status"] == "UNFETCHABLE"),
            "leads_not_scored": len(LEADS),
            "clauses_occupied": sum(1 for c in clauses.values() if c["status"] == "OCCUPIED"),
            "clauses_retired": sum(1 for c in clauses.values() if c["status"] == "RETIRED"),
            "clauses_unpriced": sum(1 for c in clauses.values() if c["status"] == "UNPRICED"),
            "clauses_free": sum(1 for c in clauses.values() if c["status"] == "FREE")},
 "clauses": clauses,
 "conjunction": {"status": conj_status, "one_source_does_all": one_source_all, "surviving_clauses": surviving, "deleted_clauses": deleted},
 "sentence": {"status": "RETIRED" if fatal else ("SURVIVES_WITHOUT_" + "_".join(deleted) if deleted else "SURVIVES"),
              "licensed_form": "we know of no ... (never 'first', 'novel' or 'revolutionary')",
              "text": None if fatal else SENTENCE},
 "sources": sources,
 "leads_not_scored": LEADS,
}
path = "papers/plates/sand_prior_art_survey.json"
with open(path, "w", encoding="utf-8", newline="\n") as fh:
    json.dump(out, fh, indent=1, ensure_ascii=False)
    fh.write("\n")
print(json.dumps(out["counts"], indent=1))
print({c: v["status"] for c, v in clauses.items()}, out["conjunction"]["status"], out["sentence"]["status"])
print("wrote", path)
