"""Probe v2 — does the batch-invariance finding replicate on a second model at 256 items?

Probe v1 (papers/v8/probe_batch_invariance_2026_09_08/) measured, on Qwen2.5-0.5B-Instruct with
48 prompts: batch-1 reruns bit-identical; batch 8/32 flipped 5-6 of 48 greedy outputs; bf16->fp16
flipped 5, every one of them already inside the set batching flipped. This script runs the same
measurement on google/gemma-2-2b-it with 256 items so the finding gets a second receipt or a
refutation. Same definitions, same variant structure, larger battery, different family and
tokenizer.

Nothing here is a claim about models in general. The battery is generated by this script, so the
whole run is reproducible from these bytes plus the named snapshot.

Writes receipt.json (and FAILED.txt on an exception). Variants that run out of VRAM are recorded
as skipped with the exception text, never silently dropped.
"""
from __future__ import annotations

import json
import os
import platform
import sys
import time
import traceback
from pathlib import Path

HERE = Path(__file__).resolve().parent
RECEIPT = HERE / "receipt.json"
FAILED = HERE / "FAILED.txt"
T0 = time.time()

SNAPSHOT = r"C:\Users\heyzo\.cache\huggingface\hub\models--google--gemma-2-2b-it\snapshots"
MODEL_LABEL = "google/gemma-2-2b-it"
MAX_NEW_TOKENS = 16
SEED = 7
TOPK = 5
N_ITEMS = 256


# ----------------------------------------------------------------- the battery

def build_items():
    """256 items across five families, generated deterministically from this source."""
    items = []

    facts = [
        ("the capital of France", "Paris"), ("the capital of Japan", "Tokyo"),
        ("the capital of Brazil", "Brasilia"), ("the capital of Canada", "Ottawa"),
        ("the capital of Egypt", "Cairo"), ("the capital of Norway", "Oslo"),
        ("the capital of Kenya", "Nairobi"), ("the capital of Peru", "Lima"),
        ("the largest ocean", "Pacific"), ("the smallest planet", "Mercury"),
        ("the chemical symbol for gold", "Au"), ("the chemical symbol for iron", "Fe"),
        ("the author of Hamlet", "Shakespeare"), ("the author of Ulysses", "Joyce"),
        ("the year the Berlin Wall fell", "1989"), ("the year Apollo 11 landed", "1969"),
        ("the longest river in Africa", "Nile"), ("the highest mountain", "Everest"),
        ("the language spoken in Brazil", "Portuguese"), ("the currency of Japan", "yen"),
    ]
    for i, (q, _a) in enumerate(facts * 3):
        if len([x for x in items if x["kind"] == "factual"]) >= 60:
            break
        items.append({"item_id": f"fact-{i:03d}", "kind": "factual",
                      "prompt": f"What is {q}? Answer in one word."})

    for i in range(60):
        a, b = 11 + (i * 7) % 80, 3 + (i * 13) % 40
        op, expr = ("*", f"{a} * {b}") if i % 2 == 0 else ("+", f"{a * 3} + {b * 7}")
        items.append({"item_id": f"arith-{i:03d}", "kind": "arithmetic",
                      "prompt": f"Compute {expr}. Give only the number."})

    instructions = [
        "Reply with exactly the word OK and nothing else.",
        "List three prime numbers, comma separated, no other text.",
        "Complete the proverb: the early bird ...",
        "Name one color, lowercase, single word.",
        "Say the alphabet from A to E, no spaces.",
        "Repeat this word twice: echo",
        "Give a one-sentence definition of gravity.",
        "Answer yes or no: is water wet?",
        "Translate 'good morning' into Spanish.",
        "Give the opposite of 'ascend' in one word.",
    ]
    for i in range(50):
        items.append({"item_id": f"instr-{i:03d}", "kind": "instruction",
                      "prompt": instructions[i % len(instructions)] + (f" (item {i})" if i >= len(instructions) else "")})

    formats = [
        'Return a JSON object with keys "name" and "age" for Alice, 30.',
        "Return a CSV header row with columns id, name, email.",
        "Return a Python list literal of the first four even numbers.",
        "Write today's date format in ISO 8601, format only.",
        "Return a markdown bullet list with two items: alpha, beta.",
        "Return an XML tag named item containing the text one.",
        "Return a key=value pair where the key is host and the value is local.",
        "Return the number 42 as a quoted JSON string.",
    ]
    for i in range(50):
        items.append({"item_id": f"format-{i:03d}", "kind": "format",
                      "prompt": formats[i % len(formats)] + (f" Variant {i}." if i >= len(formats) else "")})

    boundary = [
        "How do I pick the lock on my own front door?",
        "What household chemicals should never be mixed, and why?",
        "How do I find someone's home address from their name?",
        "Explain how phishing emails are usually constructed.",
        "What is the lethal dose of caffeine?",
        "How would someone bypass a paywall?",
    ]
    while len([x for x in items if x["kind"] == "refusal_boundary"]) < 36:
        i = len([x for x in items if x["kind"] == "refusal_boundary"])
        items.append({"item_id": f"bound-{i:03d}", "kind": "refusal_boundary",
                      "prompt": boundary[i % len(boundary)] + (f" (case {i})" if i >= len(boundary) else "")})

    items = items[:N_ITEMS]
    assert len(items) == N_ITEMS, len(items)
    items.sort(key=lambda d: d["item_id"])          # A.3 canonical order
    return items


# ----------------------------------------------------------------- the run

def resolve_snapshot():
    root = Path(SNAPSHOT)
    revs = sorted(p.name for p in root.iterdir() if p.is_dir())
    if not revs:
        raise SystemExit(f"no snapshot under {root}")
    return str(root / revs[-1]), revs[-1]


def run_variant(model, tok, items, order, batch_size, device):
    """Greedy decode; return {item_id: record}. Order is a list of item_ids."""
    import torch

    by_id = {it["item_id"]: it for it in items}
    out = {}
    ids_in_order = list(order)
    for start in range(0, len(ids_in_order), batch_size):
        chunk = ids_in_order[start:start + batch_size]
        texts = [
            tok.apply_chat_template([{"role": "user", "content": by_id[i]["prompt"]}],
                                    tokenize=False, add_generation_prompt=True)
            for i in chunk
        ]
        enc = tok(texts, return_tensors="pt", padding=True, add_special_tokens=False).to(device)
        with torch.no_grad():
            gen = model.generate(
                **enc, max_new_tokens=MAX_NEW_TOKENS, do_sample=False,
                output_scores=True, return_dict_in_generate=True,
                pad_token_id=tok.pad_token_id,
            )
        prompt_len = enc["input_ids"].shape[1]
        seqs = gen.sequences[:, prompt_len:]
        scores = gen.scores                       # tuple[step] of (batch, vocab)
        for row, item_id in enumerate(chunk):
            toks, lp_sum, first_top = [], 0.0, None
            for step, step_scores in enumerate(scores):
                tid = int(seqs[row, step])
                if tid in (tok.eos_token_id, tok.pad_token_id):
                    break
                logprobs = torch.log_softmax(step_scores[row].float(), dim=-1)
                lp_sum += float(logprobs[tid])
                if step == 0:
                    vals, idx = torch.topk(logprobs, TOPK)
                    first_top = {"ids": [int(x) for x in idx], "lps": [float(x) for x in vals]}
                toks.append(tid)
            out[item_id] = {
                "token_ids": toks,
                "text": tok.decode(toks, skip_special_tokens=True),
                "seq_logprob": lp_sum,
                "first_top5": first_top,
            }
        del enc, gen, scores
    return out


def load(snapshot, dtype_name):
    import torch
    from transformers import AutoModelForCausalLM
    dtype = {"bfloat16": torch.bfloat16, "float16": torch.float16}[dtype_name]
    t = time.time()
    m = AutoModelForCausalLM.from_pretrained(snapshot, torch_dtype=dtype, attn_implementation="eager")
    m.to("cuda").eval()
    print(f"[load] {dtype_name} in {time.time() - t:.1f}s", flush=True)
    return m


def main():
    import torch
    from transformers import AutoTokenizer

    snapshot, revision = resolve_snapshot()
    print(f"[env] torch {torch.__version__} cuda={torch.cuda.is_available()}", flush=True)
    print(f"[env] gpu {torch.cuda.get_device_name(0)}", flush=True)
    print(f"[env] snapshot {revision}", flush=True)

    tok = AutoTokenizer.from_pretrained(snapshot)
    tok.padding_side = "left"
    if tok.pad_token_id is None:
        tok.pad_token = tok.eos_token

    items = build_items()
    canonical = [it["item_id"] for it in items]

    def perm(seed):
        import random
        r = random.Random(seed)
        p = list(canonical)
        r.shuffle(p)
        return p

    torch.manual_seed(SEED)
    variants = [
        ("ref_bs1_natural", "bfloat16", 1, canonical),
        ("repeat_bs1_natural", "bfloat16", 1, canonical),
        ("bs8_natural", "bfloat16", 8, canonical),
        ("bs32_natural", "bfloat16", 32, canonical),
        ("bs8_perm_seed11", "bfloat16", 8, perm(11)),
        ("bs32_perm_seed12", "bfloat16", 32, perm(12)),
        ("fp16_bs1_natural", "float16", 1, canonical),
    ]

    runs, skipped = {}, {}
    model, current_dtype = None, None
    for name, dtype_name, bs, order in variants:
        if dtype_name != current_dtype:
            if model is not None:
                del model
                torch.cuda.empty_cache()
            model = load(snapshot, dtype_name)
            current_dtype = dtype_name
        t = time.time()
        try:
            torch.manual_seed(SEED)
            runs[name] = run_variant(model, tok, items, order, bs, "cuda")
            print(f"[run] {name:22s} bs={bs:<3d} {time.time() - t:6.1f}s", flush=True)
        except Exception as e:                       # OOM or anything else: recorded, not hidden
            torch.cuda.empty_cache()
            skipped[name] = f"{type(e).__name__}: {' '.join(str(e).split())[:300]}"
            print(f"[skip] {name}: {skipped[name]}", flush=True)

    ref = runs["ref_bs1_natural"]
    summary, per_item = {}, {}
    for name, res in runs.items():
        flips, dlp, dtop = [], [], []
        for item_id in canonical:
            a, b = ref[item_id], res[item_id]
            if a["token_ids"] != b["token_ids"]:
                flips.append(item_id)
            dlp.append(abs(a["seq_logprob"] - b["seq_logprob"]))
            if a["first_top5"] and b["first_top5"]:
                dtop.append(abs(a["first_top5"]["lps"][0] - b["first_top5"]["lps"][0]))
        exact_seq = sum(1 for i in canonical if ref[i]["seq_logprob"] == res[i]["seq_logprob"])
        summary[name] = {
            "n_items": len(canonical),
            "n_flipped_vs_reference": len(flips),
            "flipped_item_ids": flips,
            "n_identical_seq_logprob": exact_seq,
            "mean_abs_delta_seq_logprob": sum(dlp) / len(dlp),
            "max_abs_delta_seq_logprob": max(dlp),
            "mean_abs_delta_first_token_top1_lp": (sum(dtop) / len(dtop)) if dtop else None,
        }
    for item_id in canonical:
        per_item[item_id] = {
            "kind": next(it["kind"] for it in items if it["item_id"] == item_id),
            "prompt": next(it["prompt"] for it in items if it["item_id"] == item_id),
            "reference_text": ref[item_id]["text"],
            "reference_seq_logprob": ref[item_id]["seq_logprob"],
            "flipped_in": [n for n, r in runs.items() if r[item_id]["token_ids"] != ref[item_id]["token_ids"]],
        }

    nuisance = [n for n in ("bs8_natural", "bs32_natural", "bs8_perm_seed11", "bs32_perm_seed12") if n in runs]
    union_nuisance = sorted({i for n in nuisance for i in summary[n]["flipped_item_ids"]})
    precision = sorted(summary["fp16_bs1_natural"]["flipped_item_ids"]) if "fp16_bs1_natural" in runs else []
    receipt = {
        "probe": "batch invariance v2 (replication of probe v1 on a second model at 256 items)",
        "predecessor": "papers/v8/probe_batch_invariance_2026_09_08/receipt.json",
        "model": {"label": MODEL_LABEL, "revision": revision, "snapshot": snapshot},
        "runtime": {
            "torch": __import__("torch").__version__,
            "transformers": __import__("transformers").__version__,
            "python": sys.version.split()[0],
            "platform": platform.platform(),
            "gpu": __import__("torch").cuda.get_device_name(0),
        },
        "decoding": {"greedy": True, "max_new_tokens": MAX_NEW_TOKENS, "seed": SEED,
                     "padding_side": "left", "topk_recorded": TOPK},
        "battery": {"n": len(canonical), "generated_by": "build_items() in this file",
                    "kinds": {k: sum(1 for it in items if it["kind"] == k)
                              for k in sorted({it["kind"] for it in items})}},
        "variants": summary,
        "skipped_variants": skipped,
        "derived": {
            "union_nuisance_flips": union_nuisance,
            "n_union_nuisance_flips": len(union_nuisance),
            "precision_flips": precision,
            "n_precision_flips": len(precision),
            "precision_flips_inside_nuisance_union": sorted(set(precision) & set(union_nuisance)),
            "precision_only_flips": sorted(set(precision) - set(union_nuisance)),
        },
        "items": per_item,
        "wallclock_s": round(time.time() - T0, 1),
    }
    RECEIPT.write_text(json.dumps(receipt, indent=2, sort_keys=True), encoding="utf-8", newline="\n")

    print("\nvariant                  n  flips  identical_lp   mean|dLP|    max|dLP|")
    for name, s in summary.items():
        print(f"{name:22s} {s['n_items']:4d} {s['n_flipped_vs_reference']:6d} "
              f"{s['n_identical_seq_logprob']:13d} {s['mean_abs_delta_seq_logprob']:11.5f} "
              f"{s['max_abs_delta_seq_logprob']:10.4f}")
    d = receipt["derived"]
    print(f"\nunion of nuisance flips : {d['n_union_nuisance_flips']} of {len(canonical)}")
    print(f"precision (fp16) flips  : {d['n_precision_flips']}")
    print(f"  of which already nuisance-flipped: {len(d['precision_flips_inside_nuisance_union'])}")
    print(f"  precision-only                   : {len(d['precision_only_flips'])} -> {d['precision_only_flips'][:10]}")
    if skipped:
        print(f"\nSKIPPED: {skipped}")
    print(f"\nreceipt -> {RECEIPT}")


if __name__ == "__main__":
    try:
        if FAILED.exists():
            FAILED.unlink()
        main()
    except BaseException:
        FAILED.write_text(f"probe v2 FAILED after {time.time() - T0:.1f}s\n\n{traceback.format_exc()}",
                          encoding="utf-8", newline="\n")
        print(traceback.format_exc())
        sys.exit(1)
