/**
 * Cross-language determinism tests.
 *
 * These tests load reference_outputs.json (generated by the Python
 * classifier on 6 demo trajectories) and verify the TypeScript
 * classifier produces identical results.
 *
 * This is the critical correctness gate. If any test fails, the
 * TypeScript port disagrees with Python.
 */

import { describe, it, expect } from "vitest";
import { CentroidClassifier } from "../src/classifier";
import { StyxxRuntime } from "../src/runtime";
import { observe, observeRaw } from "../src/observe";
import { CATEGORIES, PHASE_TOKEN_CUTOFFS } from "../src/types";
import type { Trajectories, PhaseName } from "../src/types";
import fixtures from "./fixtures/reference_outputs.json";

const TOLERANCE = 1e-4; // floating point tolerance for cross-language comparison

describe("CentroidClassifier — cross-language determinism", () => {
  const classifier = new CentroidClassifier();

  for (const [kind, fixture] of Object.entries(fixtures)) {
    const input = (fixture as any).input as Trajectories;
    const expected = (fixture as any).output;

    describe(`fixture: ${kind}`, () => {
      it("phase1 predicted_category matches Python", () => {
        const reading = classifier.classify(input, "phase1_preflight");
        expect(reading.predicted_category).toBe(
          expected.phase1_pre.predicted_category
        );
      });

      it("phase1 confidence matches Python within tolerance", () => {
        const reading = classifier.classify(input, "phase1_preflight");
        expect(reading.confidence).toBeCloseTo(
          expected.phase1_pre.confidence,
          3
        );
      });

      it("phase1 distances match Python within tolerance", () => {
        const reading = classifier.classify(input, "phase1_preflight");
        for (const cat of CATEGORIES) {
          const pyDist = expected.phase1_pre.distances[cat];
          const tsDist = reading.distances[cat];
          expect(Math.abs(tsDist - pyDist)).toBeLessThan(TOLERANCE);
        }
      });

      if (expected.phase4_late !== null) {
        it("phase4 predicted_category matches Python", () => {
          const reading = classifier.classify(input, "phase4_late");
          expect(reading.predicted_category).toBe(
            expected.phase4_late.predicted_category
          );
        });

        it("phase4 confidence matches Python within tolerance", () => {
          const reading = classifier.classify(input, "phase4_late");
          expect(reading.confidence).toBeCloseTo(
            expected.phase4_late.confidence,
            3
          );
        });
      }
    });
  }
});

describe("StyxxRuntime", () => {
  const runtime = new StyxxRuntime();

  it("produces Vitals with correct phase activation", () => {
    const input = (Object.values(fixtures)[0] as any).input as Trajectories;
    const vitals = runtime.runOnTrajectories(input);
    expect(vitals.phase1_pre).toBeTruthy();
    if (input.entropy.length >= 25) {
      expect(vitals.phase4_late).toBeTruthy();
    }
  });

  it("short trajectory skips later phases", () => {
    const short: Trajectories = {
      entropy: [2.0, 1.5, 1.0],
      logprob: [-0.5, -0.3, -0.2],
      top2_margin: [0.4, 0.5, 0.6],
    };
    const vitals = runtime.runOnTrajectories(short);
    expect(vitals.phase1_pre).toBeTruthy();
    expect(vitals.phase2_early).toBeNull();
    expect(vitals.phase3_mid).toBeNull();
    expect(vitals.phase4_late).toBeNull();
  });

  it("gate returns pending for short trajectory", () => {
    const short: Trajectories = {
      entropy: [2.0],
      logprob: [-0.5],
      top2_margin: [0.4],
    };
    const vitals = runtime.runOnTrajectories(short);
    expect(vitals.gate).toBe("pending");
  });
});

describe("observeRaw", () => {
  it("produces valid Vitals from raw trajectories", () => {
    const input = (Object.values(fixtures)[0] as any).input as Trajectories;
    const vitals = observeRaw(input);
    expect(vitals).toBeTruthy();
    expect(vitals.phase1_pre.predicted_category).toBeTruthy();
  });
});

describe("observe", () => {
  it("returns null for response without logprobs", () => {
    const result = observe({ choices: [{ message: { content: "hello" } }] });
    expect(result).toBeNull();
  });

  it("returns null for garbage input", () => {
    expect(observe(null)).toBeNull();
    expect(observe(undefined)).toBeNull();
    expect(observe({})).toBeNull();
    expect(observe("string")).toBeNull();
  });
});

describe("Vitals output format", () => {
  it("asDict matches Python shape", () => {
    const input = (Object.values(fixtures)[0] as any).input as Trajectories;
    const vitals = observeRaw(input);
    const dict = vitals.asDict();

    expect(dict).toHaveProperty("phase1_pre");
    expect(dict).toHaveProperty("phase2_early");
    expect(dict).toHaveProperty("phase3_mid");
    expect(dict).toHaveProperty("phase4_late");
    expect(dict).toHaveProperty("tier_active");
    expect(dict).toHaveProperty("abort_reason");

    expect(dict.phase1_pre).toHaveProperty("predicted_category");
    expect(dict.phase1_pre).toHaveProperty("confidence");
    expect(dict.phase1_pre).toHaveProperty("distances");
    expect(dict.phase1_pre).toHaveProperty("probs");
    expect(dict.phase1_pre).toHaveProperty("margin");
  });

  it("asJson produces valid JSON", () => {
    const input = (Object.values(fixtures)[0] as any).input as Trajectories;
    const vitals = observeRaw(input);
    const json = vitals.asJson();
    const parsed = JSON.parse(json);
    expect(parsed.phase1_pre.predicted_category).toBeTruthy();
  });
});
