"""The collateral census — what agents actually change, with nothing accused.

Prereg: PREREG_collateral_census_2026_08_31.md (frozen before this file existed).
Corpus: the local AIDev shelf built by external1_harness.py.

No claim extraction, no prose, no verdict. Every changed file gets exactly one
class, resolved in the frozen order. G-C1 (the fidelity suite) runs first and
the census refuses to run until it passes.

  python papers/closed-model-frontier/collateral_census.py
"""
from __future__ import annotations

import hashlib
import json
import re
import sqlite3
import sys
from collections import Counter, defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
DB = HERE / "external1_shelf.sqlite"
OUT = HERE / "collateral_census.json"
FIDELITY = HERE / "collateral_census_fidelity.json"

# ── the frozen lists (quoted in full in the RESULT) ─────────────────────────
LOCKFILES = frozenset({
    "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "npm-shrinkwrap.json",
    "cargo.lock", "poetry.lock", "gemfile.lock", "go.sum", "composer.lock",
    "pipfile.lock", "gradle.lockfile", "packages.lock.json", "flake.lock",
    "mix.lock", "pubspec.lock", "podfile.lock", "uv.lock", "bun.lockb",
    "requirements.txt.lock", "conan.lock",
})
GENERATED_SEGMENTS = (
    "/dist/", "/build/", "/generated/", "/gen/", "/__generated__/",
    "/node_modules/", "/vendor/", "/.next/", "/target/debug/", "/target/release/",
    "/coverage/", "/.terraform/", "/site-packages/",
)
GENERATED_SUFFIX = (
    "_pb2.py", "_pb2_grpc.py", ".pb.go", ".pb.cc", ".pb.h", ".g.dart",
    ".freezed.dart", ".designer.cs", ".generated.ts", ".gen.go", "_generated.go",
    ".min.js", ".min.css", ".map",
)
GENERATED_MARKERS = (
    "code generated by", "do not edit", "@generated", "autogenerated",
    "auto-generated", "generated by protoc", "this file was automatically generated",
)
SNAPSHOT_SEGMENTS = ("/__snapshots__/", "/snapshots/", "/testdata/", "/fixtures/golden/")
SNAPSHOT_SUFFIX = (".snap", ".approved.txt", ".golden", ".ambr", ".approved.json")
MIGRATION_SEGMENTS = ("/migrations/", "/migrate/", "/db/migrate/", "/alembic/versions/")
MIGRATION_NAME = re.compile(r"^(?:V?\d{4,}[-_]|\d{8,14}[-_])")

CLASSES = ("lockfile", "generated", "snapshot", "migration",
           "whitespace-equivalent", "substantive")


def _norm(path: str) -> str:
    return "/" + (path or "").replace("\\", "/").strip("/").lower()


def _ws_equivalent(patch: str) -> bool:
    """Added and removed content identical once all whitespace is removed.

    Deliberately narrower than 'formatter-only' (which needs per-language
    parsing) — see the prereg. A file with no +/- lines is not ws-equivalent.
    """
    if not patch:
        return False
    add, rem = [], []
    for line in patch.splitlines():
        if line.startswith("+") and not line.startswith("+++"):
            add.append(line[1:])
        elif line.startswith("-") and not line.startswith("---"):
            rem.append(line[1:])
    if not add or not rem:
        return False
    strip = re.compile(r"\s+")
    return strip.sub("", "".join(add)) == strip.sub("", "".join(rem))


def classify(path: str, patch: str) -> str:
    """Exactly one class, frozen resolution order, first match wins."""
    p = _norm(path)
    name = p.rsplit("/", 1)[-1]

    if name in LOCKFILES:
        return "lockfile"
    if any(seg in p for seg in GENERATED_SEGMENTS) or p.endswith(GENERATED_SUFFIX):
        return "generated"
    head = (patch or "")[:400].lower()
    if any(m in head for m in GENERATED_MARKERS):
        return "generated"
    if any(seg in p for seg in SNAPSHOT_SEGMENTS) or p.endswith(SNAPSHOT_SUFFIX):
        return "snapshot"
    if any(seg in p for seg in MIGRATION_SEGMENTS) or MIGRATION_NAME.match(name):
        return "migration"
    if _ws_equivalent(patch):
        return "whitespace-equivalent"
    return "substantive"


# ── G-C1: the fidelity suite, run before any corpus number ─────────────────
FIXTURES = [
    ("package-lock.json", "+  \"x\": 1\n", "lockfile"),
    ("sub/dir/yarn.lock", "+dep@1\n", "lockfile"),
    ("src/dist/app.js", "+var x=1\n", "generated"),
    ("api/service_pb2.py", "+X = 1\n", "generated"),
    ("src/thing.ts", "// Code generated by protoc. DO NOT EDIT.\n+x\n", "generated"),
    ("tests/__snapshots__/a.snap", "+expected\n", "snapshot"),
    ("t/render.approved.txt", "+out\n", "snapshot"),
    ("db/migrations/001_init.sql", "+CREATE TABLE t;\n", "migration"),
    ("sql/20240102_add_col.sql", "+ALTER TABLE t;\n", "migration"),
    ("src/main.py", "-def f(x):\n+def f( x ):\n", "whitespace-equivalent"),
    ("src/main.py", "-def f(x):\n+def g(x):\n", "substantive"),
    ("src/new.py", "+def f():\n", "substantive"),
    ("README.md", "", "substantive"),
    # order matters: a lock inside a generated dir is still a lock (rule 1 first)
    ("build/package-lock.json", "+x\n", "lockfile"),
    # and a snapshot inside dist is generated (rule 2 precedes rule 3)
    ("dist/__snapshots__/a.snap", "+x\n", "generated"),
]


def fidelity() -> dict:
    misses = []
    for path, patch, want in FIXTURES:
        got = classify(path, patch)
        if got != want:
            misses.append({"path": path, "want": want, "got": got})
    # G-C1 also re-checks the file-status folding the same-day correction fixed
    sys.path.insert(0, str(HERE))
    from external1_harness import _fold_statuses
    fold_cases = [
        ([("a.py", "added", ""), ("a.py", "modified", "")], {"a.py": "added"}),
        ([("b.py", "modified", ""), ("b.py", "removed", "")], {"b.py": "removed"}),
        ([("c.py", "modified", ""), ("c.py", "modified", "")], {"c.py": "modified"}),
        ([("d.py", "added", ""), ("d.py", "removed", "")], {"d.py": "modified"}),
        ([("e.py", "renamed", "")], {"e.py": "modified"}),
    ]
    fold_misses = []
    for rows, want in fold_cases:
        got = _fold_statuses(rows)
        if got != want:
            fold_misses.append({"rows": str(rows), "want": want, "got": got})
    out = {"gate": "G-C1 fidelity", "fixtures": len(FIXTURES),
           "classification_misses": misses,
           "status_fold_cases": len(fold_cases), "status_fold_misses": fold_misses,
           "pass": not misses and not fold_misses}
    FIDELITY.write_text(json.dumps(out, indent=1) + "\n", encoding="utf-8")
    return out


def bucket(repo_url: str) -> int:
    n = (repo_url or "").strip().rstrip("/").lower()
    return int(hashlib.sha256(n.encode("utf-8")).hexdigest()[:8], 16) % 10


def main() -> int:
    fid = fidelity()
    print(json.dumps(fid, indent=1))
    if not fid["pass"]:
        print("\nG-C1 FAILED — the census does not run.")
        return 1
    print("G-C1 PASS — proceeding.\n")

    con = sqlite3.connect(DB)
    per_agent = defaultdict(Counter)
    per_agent_prs = defaultdict(Counter)
    totals = Counter()
    pr_has = Counter()
    excl = Counter()
    n_pr = 0

    for pid, agent, url in con.execute("SELECT id, agent, html_url FROM pr"):
        rows = con.execute("SELECT filename, status, patch FROM f WHERE pr_id=?",
                           (pid,)).fetchall()
        if not rows:
            excl["no_file_records"] += 1
            continue
        seen = {}
        for fn, _st, patch in rows:
            if not fn:
                excl["empty_filename"] += 1
                continue
            seen.setdefault(fn, []).append(patch or "")
        if not seen:
            excl["no_usable_files"] += 1
            continue
        n_pr += 1
        a = agent or "?"
        here = set()
        for fn, patches in seen.items():
            cls = classify(fn, "\n".join(patches))
            assert cls in CLASSES, f"unresolved class for {fn!r}"      # G-C3
            totals[cls] += 1
            per_agent[a][cls] += 1
            here.add(cls)
        for cls in here:
            pr_has[cls] += 1
            per_agent_prs[a][cls] += 1

    con.close()
    n_files = sum(totals.values())
    payload = {
        "prereg": "PREREG_collateral_census_2026_08_31.md",
        "corpus": {"dataset": "hao-li/AIDev", "license": "CC-BY-4.0"},
        "contains_accusation": False,                                  # G-C4
        "pull_requests": n_pr,
        "excluded": dict(excl),
        "changed_files": n_files,
        "by_class": dict(totals),
        "share_of_files": {k: round(v / n_files, 4) for k, v in totals.items()},
        "prs_containing_class": dict(pr_has),
        "share_of_prs": {k: round(v / n_pr, 4) for k, v in pr_has.items()},
        "per_agent": {a: {"files": dict(c),
                          "share_of_files": {k: round(v / sum(c.values()), 4)
                                             for k, v in c.items()},
                          "prs_containing": dict(per_agent_prs[a])}
                      for a, c in sorted(per_agent.items())},
        "note": ("whitespace-equivalent is a LOWER BOUND on formatting churn — "
                 "reformatting that reorders tokens or rewraps lines is classified "
                 "substantive here. No claim was read; nothing is accused."),
    }
    # G-C3: the classes must sum to the file count
    assert sum(payload["by_class"].values()) == n_files
    OUT.write_text(json.dumps(payload, indent=1) + "\n", encoding="utf-8")

    print(f"pull requests: {n_pr}   changed files: {n_files}")
    for cls in CLASSES:
        n = totals.get(cls, 0)
        print(f"  {cls:22s} {n:8d}  {n/n_files:6.2%} of files  "
              f"{pr_has.get(cls,0)/n_pr:6.2%} of PRs")
    print(f"-> {OUT.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
