"""The one case fold styxx/diffgate.py and web/gate/diffgate.js compare two header paths with.

NOTE_path2_tenth_pass_2026_09_27 (K-2). Y-1 (NOTE_path2_eighth_pass) abstains the file-list claims where two header
paths that differ only in case are one key, and it asked each runtime which paths those are, through the key's own
lower-casing. The runtimes read different Unicode versions (13.0.0 on Python 3.9 and 3.10, 14.0.0 on 3.11, 15.0.0 on
3.12, 15.1.0 on 3.13, 16.0.0 on 3.14 and on Node 24), and 67 code points lower-case differently among them, so a diff
naming U+10D50 and U+10D70 was a collision in the port and none in Python 3.12, and the file-list claims abstained in
one port only. Both ports now fold a header path with the table below, the same string byte for byte, and neither
asks its runtime. The key itself is unchanged (it is main's: the runtime's lower case).

The table is Unicode 16.0.0's lowercase mapping of each code point (CPython 3.14's `chr(c).lower()`, the full mapping,
so U+0130 folds to U+0069 U+0307), and U+03C2 folds to U+03C3, because both runtimes lower-case U+03A3 to either by
its context. It is sound on every supported runtime -- a pair of paths any of them keys alike, it folds alike -- and
web/gate/gen_fold.py's docstring says why, and what the test suite checks. The block between the two marker lines is
the generator's output: do not edit it by hand (`gen_fold.py --check` and tests/test_diffgate_path2.py hold it, the
port's copy and the generator to the same bytes).
"""
from __future__ import annotations

# FOLD TABLE GENERATED by web/gate/gen_fold.py -- do not edit by hand
UNICODE_VERSION = "16.0.0"
FOLD_SHA256 = "a52cda82375292f71230e7e781acc24760084994812e083870b7419bdc5d5fd6"
FOLD = (
    "1t:q:w:1,5c:n:w:1,60:7:w:1,74:o:1:2,8g=2x.lj,8i:3:1:2,8p:8:1:2,96:n:1:2,ag:1:-3d:1,ah:3:1:2,ap:1"
    ":5u:1,aq:2:1:2,au:1:5q:1,av:1:1:1,ax:2:5p:1,az:1:1:1,b2:1:27:1,b3:1:5m:1,b4:1:5n:1,b5:1:1:1,b7:1"
    ":5p:1,b8:1:5r:1,ba:1:5v:1,bb:1:5t:1,bc:1:1:1,bg:1:5v:1,bh:1:5x:1,bj:1:5y:1,bk:3:1:2,bq:1:62:1,br"
    ":1:1:1,bt:1:62:1,bw:1:1:1,by:1:62:1,bz:1:1:1,c1:2:61:1,c3:2:1:2,c7:1:63:1,c8:1:1:1,cc:1:1:1,ck:1"
    ":2:1,cl:1:1:1,cn:1:2:1,co:1:1:1,cq:1:2:1,cr:9:1:2,da:9:1:2,dt:1:2:1,du:2:1:2,dy:1:-2p:1,dz:1:-1k"
    ":1,e0:k:1:2,f4:1:-3m:1,f6:9:1:2,fu:1:8bv:1,fv:1:1:1,fx:1:-4j:1,fy:1:8bs:1,g1:1:1:1,g3:1:-5f:1,g4"
    ":1:1x:1,g5:1:1z:1,g6:5:1:2,og:2:1:2,om:1:1:1,ov:1:38:1,p2:1:12:1,p4:3:11:1,p8:1:1s:1,pa:2:1r:1,p"
    "d:h:w:1,pv:9:w:1,qq:1:1:1,r3:1:8:1,rc:c:1:2,s4:1:-1o:1,s7:1:1:1,s9:1:-7:1,sa:1:1:1,sd:3:-3m:1,sg"
    ":g:28:1,sw:w:w:1,v4:h:1:2,wa:r:1:2,xs:1:f:1,xt:7:1:2,y8:1c:1:2,10x:12:1c:1,3a8:12:5ls:1,3bb:1:5l"
    "s:1,3bh:1:5ls:1,3vk:28:tzk:1,3xs:6:8:1,5mx:1:1:1,5n4:17:-2bk:1,5od:3:-2bk:1,5xc:23:1:2,61q:1:-5v"
    "j:1,61s:1c:1:2,64o:8:-8:1,654:6:-8:1,65k:8:-8:1,660:8:-8:1,66g:6:-8:1,66x:4:-8:2,67c:8:-8:1,688:"
    "8:-8:1,68o:8:-8:1,694:8:-8:1,69k:2:-8:1,69m:2:-22:1,69o:1:-9:1,6a0:4:-2e:1,6a4:1:-9:1,6ag:2:-8:1"
    ",6ai:2:-2s:1,6aw:2:-8:1,6ay:2:-34:1,6b0:1:-7:1,6bc:2:-3k:1,6be:2:-3i:1,6bg:1:-9:1,6jq:1:-5st:1,6"
    "ju:1:-6gv:1,6jv:1:-6di:1,6k2:1:s:1,6lc:g:g:1,6mb:1:1:1,792:q:q:1,8ow:1c:1c:1,8rk:1:1:1,8rm:1:-8a"
    "f:1,8rn:1:-2xy:1,8ro:1:-89z:1,8rr:3:1:2,8rx:1:-8bg:1,8ry:1:-8al:1,8rz:1:-8bj:1,8s0:1:-8bi:1,8s2:"
    "1:1:1,8s5:1:1:1,8se:2:-8cf:1,8sg:1e:1:2,8vf:2:1:2,8vm:1:1:1,wu8:n:1:2,ww0:e:1:2,x0i:7:1:2,x0y:v:"
    "1:2,x2x:2:1:2,x31:1:-r9g:1,x32:5:1:2,x3f:1:1:1,x3h:1:-wmg:1,x3k:2:1:2,x3q:a:1:2,x4a:1:-wn8:1,x4b"
    ":1:-wnj:1,x4c:1:-wnf:1,x4d:1:-wn5:1,x4e:1:-wn8:1,x4g:1:-wlu:1,x4h:1:-wmi:1,x4i:1:-wlx:1,x4j:1:ps"
    ":1,x4k:8:1:2,x50:1:-1c:1,x51:1:-wn7:1,x52:1:-raw:1,x53:2:1:2,x57:1:-wo7:1,x58:1:1:1,x5c:1:1:1,x5"
    "i:3:1:2,x5o:1:-wu9:1,x6d:1:1:1,1ee9:q:w:1,1fcw:14:14:1,1fhs:10:14:1,1fn4:b:13:1,1fng:f:13:1,1fnw"
    ":7:13:1,1fo4:2:13:1,1h1c:1f:1s:1,1h74:m:w:1,1jfk:w:w:1,20cg:w:w:1,2olc:y:y:1"
)
# END OF THE FOLD TABLE


def _decode(table: str) -> dict:
    """{code point: its fold}: entries separated by ",", `S:N:D:T` N code points from S in steps of T each folding to
    itself plus D, `S=A.B` the code point S folding to the code points A, B; every number base 36."""
    out: dict = {}
    for entry in table.split(","):
        if "=" in entry:
            start, targets = entry.split("=")
            out[int(start, 36)] = "".join(chr(int(x, 36)) for x in targets.split("."))
        else:
            start, count, delta, step = (int(x, 36) for x in entry.split(":"))
            for i in range(count):
                out[start + i * step] = chr(start + i * step + delta)
    return out


MAP = _decode(FOLD)


def fold(text: str) -> str:
    """`text` with each code point folded by the table."""
    return text.translate(MAP)
