"""The one case fold styxx/diffgate.py and web/gate/diffgate.js compare two header paths with.

NOTE_path2_tenth_pass_2026_09_27 (K-2). Y-1 (NOTE_path2_eighth_pass) abstains the file-list claims where two header
paths that differ only in case are one key, and it asked each runtime which paths those are, through the key's own
lower-casing. The runtimes read different Unicode versions (13.0.0 on Python 3.9 and 3.10, 14.0.0 on 3.11, 15.0.0 on
3.12, 15.1.0 on 3.13, 16.0.0 on 3.14 and on Node 24), and 67 code points lower-case differently among them, so a diff
naming U+10D50 and U+10D70 was a collision in the port and none in Python 3.12, and the file-list claims abstained in
one port only. Both ports now fold a header path with the table below, the same string byte for byte, and neither
asks its runtime. The key itself is unchanged (it is main's: the runtime's lower case).

The table is Unicode 16.0.0's lowercase mapping of each code point (CPython 3.14's `chr(c).lower()`, the full mapping,
so U+0130 folds to U+0069 U+0307), and U+03C2 folds to U+03C3, because both runtimes lower-case U+03A3 to either by
its context. On a runtime whose Unicode is 16.0 or older it is sound -- a pair of paths such a runtime keys alike, it
folds alike -- and web/gate/gen_fold.py's docstring says why, and what the test suite checks.

NOTE_path2_thirteenth_pass_2026_09_29 (D). A runtime on a NEWER Unicode lower-cases code points 16.0.0 does not assign,
which the table cannot know (CI's Node on Unicode 17.0: U+A7CE, U+A7D2, U+A7D4, U+16EA0 to U+16EB8), so the tenth
pass's "sound on every supported runtime" was false there. Beside the fold the block carries the set of code points
Unicode 16.0.0 assigns (`ASSIGNED`, general category other than Cn), and a header path holding a code point outside it
(`unassigned`) is a path-key doubt in both ports: the file list is not sure, and every file-list and path claim
abstains. A newer runtime is covered that way: the fold is sound on the paths it still reads, which hold only assigned
code points, wherever that runtime lower-cases each assigned code point as 16.0.0 does, and the test suite checks that
premise on the runtime it runs on (every code point whose lower-casing merges beyond the fold must be unassigned).

The block between the two marker lines is the generator's output: do not edit it by hand (`gen_fold.py --check` and
tests/test_diffgate_path2.py hold it, the port's copy and the generator to the same bytes).
"""
from __future__ import annotations

from bisect import bisect_right

# FOLD TABLE GENERATED by web/gate/gen_fold.py -- do not edit by hand
UNICODE_VERSION = "16.0.0"
FOLD_SHA256 = "a52cda82375292f71230e7e781acc24760084994812e083870b7419bdc5d5fd6"
FOLD = (
    "1t:q:w:1,5c:n:w:1,60:7:w:1,74:o:1:2,8g=2x.lj,8i:3:1:2,8p:8:1:2,96:n:1:2,ag:1:-3d:1,ah:3:1:2,ap:1"
    ":5u:1,aq:2:1:2,au:1:5q:1,av:1:1:1,ax:2:5p:1,az:1:1:1,b2:1:27:1,b3:1:5m:1,b4:1:5n:1,b5:1:1:1,b7:1"
    ":5p:1,b8:1:5r:1,ba:1:5v:1,bb:1:5t:1,bc:1:1:1,bg:1:5v:1,bh:1:5x:1,bj:1:5y:1,bk:3:1:2,bq:1:62:1,br"
    ":1:1:1,bt:1:62:1,bw:1:1:1,by:1:62:1,bz:1:1:1,c1:2:61:1,c3:2:1:2,c7:1:63:1,c8:1:1:1,cc:1:1:1,ck:1"
    ":2:1,cl:1:1:1,cn:1:2:1,co:1:1:1,cq:1:2:1,cr:9:1:2,da:9:1:2,dt:1:2:1,du:2:1:2,dy:1:-2p:1,dz:1:-1k"
    ":1,e0:k:1:2,f4:1:-3m:1,f6:9:1:2,fu:1:8bv:1,fv:1:1:1,fx:1:-4j:1,fy:1:8bs:1,g1:1:1:1,g3:1:-5f:1,g4"
    ":1:1x:1,g5:1:1z:1,g6:5:1:2,og:2:1:2,om:1:1:1,ov:1:38:1,p2:1:12:1,p4:3:11:1,p8:1:1s:1,pa:2:1r:1,p"
    "d:h:w:1,pv:9:w:1,qq:1:1:1,r3:1:8:1,rc:c:1:2,s4:1:-1o:1,s7:1:1:1,s9:1:-7:1,sa:1:1:1,sd:3:-3m:1,sg"
    ":g:28:1,sw:w:w:1,v4:h:1:2,wa:r:1:2,xs:1:f:1,xt:7:1:2,y8:1c:1:2,10x:12:1c:1,3a8:12:5ls:1,3bb:1:5l"
    "s:1,3bh:1:5ls:1,3vk:28:tzk:1,3xs:6:8:1,5mx:1:1:1,5n4:17:-2bk:1,5od:3:-2bk:1,5xc:23:1:2,61q:1:-5v"
    "j:1,61s:1c:1:2,64o:8:-8:1,654:6:-8:1,65k:8:-8:1,660:8:-8:1,66g:6:-8:1,66x:4:-8:2,67c:8:-8:1,688:"
    "8:-8:1,68o:8:-8:1,694:8:-8:1,69k:2:-8:1,69m:2:-22:1,69o:1:-9:1,6a0:4:-2e:1,6a4:1:-9:1,6ag:2:-8:1"
    ",6ai:2:-2s:1,6aw:2:-8:1,6ay:2:-34:1,6b0:1:-7:1,6bc:2:-3k:1,6be:2:-3i:1,6bg:1:-9:1,6jq:1:-5st:1,6"
    "ju:1:-6gv:1,6jv:1:-6di:1,6k2:1:s:1,6lc:g:g:1,6mb:1:1:1,792:q:q:1,8ow:1c:1c:1,8rk:1:1:1,8rm:1:-8a"
    "f:1,8rn:1:-2xy:1,8ro:1:-89z:1,8rr:3:1:2,8rx:1:-8bg:1,8ry:1:-8al:1,8rz:1:-8bj:1,8s0:1:-8bi:1,8s2:"
    "1:1:1,8s5:1:1:1,8se:2:-8cf:1,8sg:1e:1:2,8vf:2:1:2,8vm:1:1:1,wu8:n:1:2,ww0:e:1:2,x0i:7:1:2,x0y:v:"
    "1:2,x2x:2:1:2,x31:1:-r9g:1,x32:5:1:2,x3f:1:1:1,x3h:1:-wmg:1,x3k:2:1:2,x3q:a:1:2,x4a:1:-wn8:1,x4b"
    ":1:-wnj:1,x4c:1:-wnf:1,x4d:1:-wn5:1,x4e:1:-wn8:1,x4g:1:-wlu:1,x4h:1:-wmi:1,x4i:1:-wlx:1,x4j:1:ps"
    ":1,x4k:8:1:2,x50:1:-1c:1,x51:1:-wn7:1,x52:1:-raw:1,x53:2:1:2,x57:1:-wo7:1,x58:1:1:1,x5c:1:1:1,x5"
    "i:3:1:2,x5o:1:-wu9:1,x6d:1:1:1,1ee9:q:w:1,1fcw:14:14:1,1fhs:10:14:1,1fn4:b:13:1,1fng:f:13:1,1fnw"
    ":7:13:1,1fo4:2:13:1,1h1c:1f:1s:1,1h74:m:w:1,1jfk:w:w:1,20cg:w:w:1,2olc:y:y:1"
)
ASSIGNED_SHA256 = "56a413ebc235c1b375e39f8faf1384e8861da0e8ce4a46b53128c0a16b76456b"
ASSIGNED = (
    "0:oo,2:6,4:7,1:1,1:k,1:b1,1:12,2:1e,2:3,1:1j,8:r,4:6,b:7i,1:1o,2:2t,e:1n,2:1d,2:f,1:s,2:1,1:b,5:"
    "v,1:2,5:6l,1:8,2:2,2:m,1:7,1:1,3:4,2:9,2:2,2:4,8:1,4:2,1:5,2:p,2:3,1:6,4:2,2:m,1:7,1:2,1:2,1:2,2"
    ":1,1:5,4:2,2:3,3:1,7:4,1:1,7:h,a:3,1:9,1:3,1:m,1:7,1:2,1:5,2:a,1:3,1:3,2:1,f:4,2:c,7:7,1:3,1:8,2"
    ":2,2:m,1:7,1:2,1:5,2:9,2:2,2:3,7:3,4:2,1:5,2:i,a:2,1:6,3:3,1:4,3:2,1:1,1:2,3:2,3:3,3:c,4:5,3:3,1"
    ":4,2:1,6:1,e:l,5:d,1:3,1:n,1:g,2:9,1:3,1:4,7:2,1:3,2:1,2:4,2:a,7:m,1:3,1:n,1:a,1:5,2:9,1:3,1:4,7"
    ":2,6:2,1:4,2:a,1:3,c:d,1:3,1:1f,1:3,1:6,4:g,2:q,1:3,1:i,3:o,1:9,1:1,2:7,3:1,4:6,1:1,1:8,6:a,2:3,"
    "c:1m,4:t,11:2,1:1,1:5,1:o,1:1,1:n,2:5,1:1,1:7,1:a,2:4,w:20,1:10,4:13,1:10,1:f,1:d,11:5i,1:1,5:1,"
    "2:ah,1:4,2:7,1:1,1:4,2:15,1:4,2:x,1:4,2:7,1:1,1:4,2:f,1:1l,1:4,2:1v,2:w,3:q,6:2e,2:6,2:il,3:2h,7"
    ":m,9:o,9:k,c:d,1:3,1:2,c:2m,2:a,6:a,6:q,6:2h,7:17,5:1y,a:v,1:c,4:c,4:1,3:16,2:5,b:18,4:q,6:b,3:1"
    "q,2:1t,1:t,2:b,6:a,6:e,2:v,1d:25,1:4m,8:1o,3:f,3:1q,5:17,2:b,8:17,5:eu,2:6,2:12,2:6,2:8,1:1,1:1,"
    "1:1,1:v,2:1h,1:f,1:e,2:6,1:j,2:3,1:9,1:2t,1:c,2:r,1:d,3:x,f:x,f:3w,4:ii,m:b,l:1ec,2:w,1:9p,5:19,"
    "1:1,5:1,2:1k,7:2,e:o,9:7,1:7,1:7,1:7,1:7,1:7,1:7,1:7,1:3i,y:q,1:2h,c:5y,q:28,1:2e,2:2v,5:17,1:2m"
    ",1:2e,9:1c,1:mlp,3:1j,9:9o,k:54,8:5q,2:2,1:1,1:8,l:1n,3:a,6:1k,8:1y,8:c,6:38,b:u,3:26,1:b,4:x,1:"
    "1j,9:e,2:a,2:2v,o:s,a:6,2:6,2:6,9:7,1:7,1:1o,4:3i,2:a,6:8mc,c:n,4:1d,4:6su,2:2y,12:7,c:5,5:q,1:5"
    ",1:1,1:2,1:2,1:3h,g:cd,2:1i,7:1,w:16,6:1f,1:j,1:4,4:5,1:3r,2:1,1:5a,3:6,2:6,2:6,2:3,3:7,1:7,a:5,"
    "2:c,1:q,1:j,1:2,1:f,2:e,y:3f,5:3,4:19,3:2g,1:d,3:1,1b:1a,3m:t,3:1d,f:s,4:10,9:u,5:17,5:u,1:11,4:"
    "e,16:4e,2:a,6:10,4:10,4:14,8:1g,b:c,1:f,1:7,1:2,1:b,1:f,1:7,1:2,3:1g,c:8n,9:m,a:8,o:6,1:16,1:9,1"
    "x:6,2:1,1:18,1:2,3:1,2:n,1:20,8:9,1c:j,1:2,5:x,3:r,5:1,1s:1k,4:k,2:1e,1:2,5:8,1:3,1:t,2:3,4:a,7:"
    "9,7:1s,w:13,4:c,9:1i,3:t,2:r,5:q,7:4,c:7,28:21,1j:1f,d:1f,7:1a,8:a,6:12,3:t,8:2,5s:v,1:16,1:3,2:"
    "2,g:3,1j:18,8:16,m:q,12:s,k:n,9:26,4:10,9:1w,a:1,2:p,7:a,6:1h,1:i,8:13,9:2o,1:k,b:i,1:1b,1q:7,1:"
    "1,1:4,1:f,1:b,6:1n,5:a,6:4,1:8,2:2,2:m,1:7,1:2,1:5,1:a,2:2,2:3,2:1,6:1,5:7,2:7,3:5,b:a,1:1,2:1,1"
    ":12,1:a,1:1,2:1,1:4,1:a,1:2,8:2,t:2k,1:5,u:20,8:a,4m:1i,2:12,y:1x,b:a,6:d,j:1m,6:a,6:k,s:r,2:f,4"
    ":n,55:1o,2s:2b,c:8,2:1,2:8,1:2,1:u,1:2,2:c,9:a,1y:8,2:1a,2:b,r:20,8:2b,d:21,7:a,52:y,e:a,6:9,1:1"
    "9,1:e,a:t,3:w,2:m,1:e,21:7,1:2,1:18,3:1,1:2,1:9,8:a,6:6,1:2,1:11,1:2,1:6,7:a,8m:p,7:h,1:15,3:t,2"
    "d:1,f:1e,d:pn,2u:33,1:5,b:5g,218:2r,d:uu,a:32z,5:g7,5a1:1m,1c6:ft,7:v,1:a,4:29,1:a,6:u,2:6,a:1y,"
    "a:a,1:7,1:l,5:j,c0:1m,5i:2j,2t:23,4:1l,7:h,1s:5,b:2,e:4qg,8:ye,15:a,6w7:4,1:7,1:2,1:83,f:1,t:3,2"
    ":1,e:4,8:b0,1s4:2z,5:d,3:9,7:a,2:8,318:6y,6:c4,24:1a,2:n,9:38,1o:6u,a:13,2:5e,l:1y,3e:k,c:k,c:2f"
    ",9:p,3r:2d,1:1z,1:2,2:1,2:2,2:4,1:c,1:1,1:7,1:1t,1:4,2:8,1:7,1:s,1:4,1:5,1:1,3:7,1:9g,2:84,2:ji,"
    "f:5,1:f,uo:v,6:6,5x:7,1:h,2:7,1:2,1:5,5:1q,x:1,34:19,3:e,2:a,4:2,8w:v,h:1m,5:1,cw:16,5y:17,4:1,d"
    "c:7,1:4,1:2,1:f,1:5h,2:g,15:24,4:a,4:2,lt:1w,24:1p,5e:4,1:r,1:2,1:1,2:1,1:a,1:4,1:1,1:1,6:1,4:1,"
    "1:1,1:1,1:3,1:2,1:1,2:1,1:1,1:1,1:1,1:1,1:2,1:1,2:4,1:7,1:4,1:4,1:1,1:a,1:h,5:3,1:5,1:h,1g:2,7i:"
    "18,4:2s,c:f,2:f,1:f,1:11,a:4u,1k:t,d:18,4:9,7:2,e:6,4a:rc,4:h,3:d,3:3b,4:2n,6:c,4:1,f:c,4:1k,8:a"
    ",6:14,8:u,2:c,4:2,1q:9g,c:e,2:d,3:a,5:1k,7:f,2:b,6:9,7:43,1:2u,sm:wyo,w:37e,6:66,2:4g2,e:5rl,f:h"
    "a,1wi:f2,15u:3t7,5:38g,f975:1,u:2o,3k:6o,1e6o:1eke,2:1eke"
)
# END OF THE FOLD TABLE


def _decode(table: str) -> dict:
    """{code point: its fold}: entries separated by ",", `S:N:D:T` N code points from S in steps of T each folding to
    itself plus D, `S=A.B` the code point S folding to the code points A, B; every number base 36."""
    out: dict = {}
    for entry in table.split(","):
        if "=" in entry:
            start, targets = entry.split("=")
            out[int(start, 36)] = "".join(chr(int(x, 36)) for x in targets.split("."))
        else:
            start, count, delta, step = (int(x, 36) for x in entry.split(":"))
            for i in range(count):
                out[start + i * step] = chr(start + i * step + delta)
    return out


MAP = _decode(FOLD)


def fold(text: str) -> str:
    """`text` with each code point folded by the table."""
    return text.translate(MAP)


def _decode_assigned(table: str) -> tuple:
    """(starts, ends): the half-open runs of assigned code points, from `G:N` entries (a run of N starting G code points
    after the previous run's end), every number base 36."""
    starts: list = []
    ends: list = []
    prev = 0
    for entry in table.split(","):
        gap, n = (int(x, 36) for x in entry.split(":"))
        starts.append(prev + gap)
        ends.append(prev + gap + n)
        prev = prev + gap + n
    return starts, ends


_STARTS, _ENDS = _decode_assigned(ASSIGNED)


def assigned(cp: int) -> bool:
    """Whether Unicode 16.0.0 assigns the code point `cp` (its general category is not Cn)."""
    i = bisect_right(_STARTS, cp) - 1
    return i >= 0 and cp < _ENDS[i]


def unassigned(text: str) -> bool:
    """NOTE_path2_thirteenth_pass (D): whether `text` holds a code point Unicode 16.0.0 does not assign -- one a runtime
    on a newer Unicode may lower-case beyond the fold. Every ASCII code point is assigned."""
    return not text.isascii() and any(not assigned(ord(ch)) for ch in text)
