"""The one Unicode table styxx/diffgate.py and web/gate/diffgate.js read a Python name with.

NOTE_path2_seventh_pass_2026_09_25. The sixth pass (W-2) made a name -- claimed in a summary or
defined on a diff line -- the Python identifier that starts there, and each port asked its runtime
which characters an identifier holds: `str.isidentifier` in the Python (Unicode 13.0 on 3.9 and 3.10,
14.0 on 3.11, 15.0 on 3.12, 15.1 on 3.13, 16.0 on 3.14) and `\\p{XID_Start}` / `\\p{XID_Continue}` in the
port (16.0 on Node 24; 15.1 or later in current browsers). One name then read two ways: "Added function
foo<U+30FB>bar." over `def foo<U+30FB>bar():` was VERIFIED in the port and CONTRADICTED in the Python.
Both ports now read the table below, which is the same string in both files, byte for byte, and neither
asks its runtime.

One run-length table over every code point, U+0000 to U+10FFFF, three properties as a mask:

    1  opens a Python identifier     str.isidentifier() of the character alone: XID_Start, or `_`
    2  continues one                 XID_Continue
    4  a word character              Python's `\\w` for a str pattern: str.isalnum(), or `_`

Each run is one number, length * 8 + mask, written in base 31, the most significant digit leading:
a digit that ends the number is one of `0-9a-u`, a digit that does not is one of `v-zA-Z`. The table is
pure ASCII and needs no escaping in either language or in a `javascript:` link.

The version is Unicode 15.0.0, the database CPython 3.12 carries (its `unicodedata.unidata_version`),
generated from that database by `web/gate/gen_xid.py`, which refuses to run on any other. It is the
newest version any Python this package supports (3.9 to 3.12) reads identifiers by, so on every
supported Python a name CPython accepts is a name this table accepts; the note says what that costs on
3.13 and later. The block between the two GENERATED lines is the generator's output: do not edit it by
hand (`gen_xid.py --check` and tests/test_diffgate_path2.py hold it, the port's copy and the generator to
the same bytes).
"""
from __future__ import annotations

from bisect import bisect_right

# GENERATED by web/gate/gen_xid.py -- do not edit by hand
UNICODE_VERSION = "15.0.0"
TABLE_SHA256 = "8df68f217cca495ab8a38ced9096213aabac4cf23927068d61397d2c9074d4cb"
TABLE = (
    "HcxowpBtw1f8BtH4fwpk8f8a8cf8s8B58D78yUdw1yayjwgwpf8fzcXuwg8ngcw08fwhfaw08f8Ac8Qk8wA38wbgwH28F1gf"
    "whFpx2Gl8a8i8i8ax2C6w1w8Cfxsw9GaAfxow1naUo8fwrgwjni8w3nxow0gfz4faCuC1gS6xsfyjxoDnxcnw1fgagAsw3fx"
    "cfqfwbzkBlqw1y2w9Bd8woxax4G2B88DiJ5qfzmfwrxpigxo8zbq8x9gngAs8x18fow8gafwrgigqfx2aw1n8w0igxongwlg"
    "f8agq8wow1ngAs8x18n8n8nga8wbw1igqoawpw88fwpxoiw0axqq8xh8w08As8x18n8wggafx48q8qgfyrnigxoxafwj8q8x"
    "9gngAs8x18n8wggafwrgigqwpqw1n8w0igxo8fwlxiaf8woow08w8on8f8nonow0oyaw1wboq8w3gfwhayjxosybwbx98w08"
    "B58zbgafwr8q8w3wpi8w0gfgnigxox2wt8fq8x98w08B58xp8wggafwr8q8w3wpiwhn8nigxo8nay3w3xh8w08Fpifwr8q8w"
    "3fw9w0awtw0igxoxe8wo8q8zroBd8xh8fgx1oaw1wj8a8x4whxogiybHjafewrw9x1x48xoF2n8f8wg8Bd8f8xpafexcfgwg"
    "8f8wr8xogw8D8fAtiwhxoxm8a8a8aw1ix98Egw1A78iwgxs8EbxaaJmGaA7fxowhwow3w8qfqnwrw0w3yiy5faxow3gF18fw"
    "9fgGa8xT58w8gx18f8w8gFp8w8gDn8w8gx18f8w8gz38Jt8w8gMggqxaxgxuozbz4RdgwooAA7gzj8Btw9Oioy2wpzrw3xaA"
    "4qxqzriy3yi8w08iy3IkDaofw1fagxowhxmzcq8axowhS6wpwgjE0afw9N9xiD78y5w1y5xixoCugwgxqGiw1Btwhy1EhB5w"
    "bw1Isxk8Chgaxowhxoybfx2yl8z6HkwbHbzex9oxozcxcy3qCuydnxoGiyly3EgA7x2xoow0xoEggxhwpGagw0z4q8Afw8aw"
    "oanqfw9wNoLixEugwogF1gwogx98f8f8f8D7gIs8x18fow08x1ow8gwow1yiw9w08x1M1izsaBucfgwlw9fxmwhyiI5ydw1a"
    "oy5zcfw1fgxp8fgbwgwhf8f8f8w8by2gw8w9wgw1f8z8FpcBwbKjP4ApACiCrEI4wXawhw8qnxacgF18fw9fgJlwpfyraB5x"
    "ax18x18x18x18x18x18x18x18DaH4cyX1w0Bexhwj8wggwgw1Rdgigw08Se8w8w9Ga8Tfow5xiDfHczbD8xmCnx68z0D8xmF"
    "2z0xPiwSWcLgAYJ5M9H3gxCkozbxonA5Hbaw1xk8D7iPriEhxhgVpgLnw9n8f8wgB6zbaw0aw8aB5wbw1aowlxiIky3iI4zm"
    "xixowhzmwoof8naxoCex4gB5ydy3Cmow3Hbylyjfxowhwgaxpxowg8Fpylxaw0ax9igxowhB5ofqI4afqniwgifafB6w0gy2"
    "wbgw0ixiwogwogwoxax18x18Ga8yqwhYsx48igxowhyvvay3B5w1HrxDG5ywlgWiEpx1y3wgw9faxp8yi8wg8f8n8n8X3Dgw"
    "A3wlwUfzkLngJ5Faxpkw1z6z4z6oiB6qD8cfcfc8cfcfcfcfcwwnzsxowpBtw1a8BtxqJlmD7owogwogwogw0E1ya8Bt8A48"
    "n8z3gyqDowvuy3Gny3Isw5zckY5awxhCmoHryraC3w1Dfw5xaCuw9F1wbw9CugEgw1x98wgFqwF0gxowhEgw1Egw1Fhx2Iky"
    "3y28z38x18n8y28z38x18nM9xNfxaAsxix9B6wo8G28xhMpwogf8Gi8nofgB5gx6B5gwtD7x2xeHcA48nw9wdAswlw1BtN2J"
    "lw1knz8gH0fq8iw9w3w88w08Cmgqw1axeAtCmk8CmsD8x98Ceiw1wdz4J5xiAsgx6A4w9x6zrAtwtPkO2J6IcybIcwpwlEgw"
    "3x2xoxIrD48G28ionObqCmxmfx2Asxsw5Buzrw3FqAkwtA5B5xaqIsytxqA9xoanifxaw3GqxswpaybBlwpxowhqEgyl8xow"
    "1fifx2E8agfxaqHjylw8w1w38ixof8fw1A9xqzr8Bly5whanaL0x18f8w88z38xpwpHby5w9xowhw38x9gngAs8x18n8wg8i"
    "fwrgigqgfwhaw9wgigwrowbwzrIszmw8w9xow1aw0CnHjA7n8fx2xowGqHbwrgxcAtw8iDoHjzeofxqxoEpGaydfwpxoItC6"
    "gytw1xokw1x1wLnGiytV2Lnxoxey3x9gfgx98n8Bdwj8igw3fafiy3xoN2x9gF9wrgwrf8faBufxkFhwrfw3x2ax2fxsH3z6"
    "ofzkO2xArxh8Eox48x4fyrxoA1w9CugAn8ylNqx18n8F1wjoa8i8wrfax2xowhwo8n8Dfwb8i8wbfwpxoxN0A4w3xaifayi8"
    "E0wrowbybxoR6fyrAhG3CQ5VaXrzcwOpQY8U8yrDXrz4awoytwxGqzVlxEVrzS2wpD78xowhPj8xowhCugwbxqHjwrxaw8y3"
    "xo8wt8Akw9A4ARhLnB2W3Oiw1afJ8wpw3yiLgn8faxqiyjwPxmx2FEmFqxhxHGpw88x18n8xIayrfCfw0gfyjw8x2yEdOBjW"
    "qw9yioxhwpxpoiwDA6GtgB0zKrwbowjx2x4gwrCnw3wC6qwvnA9y3A9WrBiwyqR58Nh8ngfgngw88ya8f8x18M08w8gx98x1"
    "8Ce8w88wg8fox18xUugBl8Bl8D78Bl8D78Bl8D78Bl8D78Bl8x9gI3zD4J8w1Hux2ayjaAlwb8ytEAsD7whwowSuwr8zegwr"
    "8i8wbw9L7DgaXsGqowrx1gxow1fxPqCuazcGiw3xoyX9Cew3xoBAfx18w88n8z38wP2gxewrFiMowrfw1xoBN4Kb8s8w5OjG"
    "n8z0wO2w88C68n8fgf8xp8w88f8fwhfw1f8f8f8w08n8fgf8f8f8f8f8n8fgw88x18w88w88f8xp8zjw9w08wg8zjzUlyfSB"
    "7xoDMpGJOnD8wyN7whwVggwLZ6yjxvBnUUozL3HLkwFypw9wyX1BABE2xv0wQPMh"
)
# END GENERATED

_ENDS = "0123456789abcdefghijklmnopqrstu"          # a digit that ends a number
_MORE = "vwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"          # a digit that does not


def decode(table: str) -> tuple[list, list]:
    """(run starts, run masks) of an encoded table; refuses one that does not cover every code point."""
    starts: list = []
    masks: list = []
    cp = value = 0
    for ch in table:
        k = _MORE.find(ch)
        if k >= 0:
            value = value * 31 + k
            continue
        k = _ENDS.find(ch)
        if k < 0:
            raise ValueError(f"not a table digit: {ch!r}")
        value = value * 31 + k
        starts.append(cp)
        masks.append(value & 7)
        cp += value >> 3
        value = 0
    if cp != 0x110000 or value:
        raise ValueError(f"the table covers {cp:#x} code points, not 0x110000")
    return starts, masks


_STARTS, _MASKS = decode(TABLE)


def mask(ch: str) -> int:
    """The table's mask for one character."""
    return _MASKS[bisect_right(_STARTS, ord(ch)) - 1]


def opens_identifier(ch: str) -> bool:
    """XID_Start, or `_`: what `str.isidentifier` asks of the opening character (Unicode 15.0.0)."""
    return bool(mask(ch) & 1)


def continues_identifier(ch: str) -> bool:
    """XID_Continue: what `str.isidentifier` asks of every later character (Unicode 15.0.0)."""
    return bool(mask(ch) & 2)


def is_word(ch: str) -> bool:
    """Python's `\\w` for a str pattern, str.isalnum() or `_` (Unicode 15.0.0)."""
    return bool(mask(ch) & 4)
