"""Generate the one Unicode table both diffgate ports read a Python name with (NOTE_path2_seventh_pass_2026_09_25).

    py -3.12 web/gate/gen_xid.py            # writes the GENERATED block of styxx/_xid.py and of web/gate/diffgate.js
    py -3.12 web/gate/gen_xid.py --check    # recomputes the table and compares both blocks; writes nothing

The table is read from ONE Unicode version, 15.0.0, the database CPython 3.12 carries, and this script
REFUSES to run under any other (`unicodedata.unidata_version` must be PINNED): the whole point is that no
runtime's tables decide a name any more, so the generator's own runtime may not either.

For every code point, three bits (styxx/_xid.py's docstring says how they are written):

    1  chr(c).isidentifier()                 XID_Start, or `_` -- the opening character of an identifier
    2  ("a" + chr(c)).isidentifier()         XID_Continue -- every later character
    4  chr(c).isalnum() or chr(c) == "_"     Python's `\\w` for a str pattern (sre: Py_UNICODE_ISALNUM or `_`)

CPython builds `str.isidentifier` from DerivedCoreProperties.txt's XID_Start and XID_Continue and `\\w` from
its alpha/decimal/digit/numeric flags, so the three bits are those properties of Unicode 15.0.0 as that
Python reads them. Both blocks carry the version and the sha256 of the table's ASCII bytes; the test suite
checks that the two blocks are identical and, under a 15.0.0 Python, that this script reproduces them.
"""
from __future__ import annotations

import hashlib
import re
import sys
import unicodedata
from pathlib import Path

PINNED = "15.0.0"
HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
PY_FILE = ROOT / "styxx" / "_xid.py"
JS_FILE = HERE / "diffgate.js"
BEGIN = "GENERATED by web/gate/gen_xid.py -- do not edit by hand"
END = "END GENERATED"
ENDS = "0123456789abcdefghijklmnopqrstu"      # a digit that ends a number
MORE = "vwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"      # a digit that does not
WIDTH = 96


def mask(c: int) -> int:
    ch = chr(c)
    return ((1 if ch.isidentifier() else 0) | (2 if ("a" + ch).isidentifier() else 0)
            | (4 if (ch.isalnum() or ch == "_") else 0))


def encode(value: int) -> str:
    out = ENDS[value % 31]
    value //= 31
    while value:
        out = MORE[value % 31] + out
        value //= 31
    return out


def table() -> str:
    if unicodedata.unidata_version != PINNED:
        sys.exit(f"gen_xid: this Python reads Unicode {unicodedata.unidata_version}; the table is pinned to "
                 f"{PINNED} (run it with py -3.12)")
    runs: list = []
    for c in range(0x110000):
        k = mask(c)
        if runs and runs[-1][0] == k:
            runs[-1][1] += 1
        else:
            runs.append([k, 1])
    return "".join(encode(n * 8 + k) for k, n in runs)


def sha(t: str) -> str:
    return hashlib.sha256(t.encode("ascii")).hexdigest()


def chunks(t: str) -> list:
    return [t[i:i + WIDTH] for i in range(0, len(t), WIDTH)]


def python_block(t: str) -> list:
    return ([f"# {BEGIN}", f'UNICODE_VERSION = "{PINNED}"', f'TABLE_SHA256 = "{sha(t)}"', "TABLE = ("]
            + [f'    "{c}"' for c in chunks(t)] + [")", f"# {END}"])


def js_block(t: str) -> list:
    body = chunks(t)
    return ([f"// {BEGIN}", f'const _XID_UNICODE_VERSION = "{PINNED}";', f'const _XID_TABLE_SHA256 = "{sha(t)}";',
             "const _XID_TABLE ="]
            + [f'  "{c}"' + (";" if i == len(body) - 1 else " +") for i, c in enumerate(body)] + [f"// {END}"])


def splice(path: Path, block: list) -> tuple[str, str]:
    """(the file as it is, the file with its GENERATED block replaced), in the file's own line ending."""
    raw = path.read_bytes().decode("utf-8")
    nl = "\r\n" if "\r\n" in raw else "\n"
    lines = raw.split(nl)
    starts = [i for i, x in enumerate(lines) if x.rstrip().endswith(BEGIN)]
    ends = [i for i, x in enumerate(lines) if x.rstrip().endswith(END)]
    if len(starts) != 1 or len(ends) != 1 or ends[0] < starts[0]:
        sys.exit(f"gen_xid: {path} needs exactly one GENERATED block")
    new = lines[:starts[0]] + block + lines[ends[0] + 1:]
    return raw, nl.join(new)


def blocks_of(text: str) -> str:
    """The GENERATED block of a file's text, newlines normalised: what the test compares."""
    m = re.search(r"[^\n]*" + re.escape(BEGIN) + r".*?" + re.escape(END), text.replace("\r\n", "\n"), re.S)
    return m.group(0) if m else ""


def main(argv: list) -> int:
    t = table()
    ok = True
    for path, block in ((PY_FILE, python_block(t)), (JS_FILE, js_block(t))):
        before, after = splice(path, block)
        same = before == after
        ok = ok and same
        if "--check" in argv:
            print(f"{path.relative_to(ROOT).as_posix():<24} {'matches' if same else 'DIFFERS'}")
        elif not same:
            path.write_bytes(after.encode("utf-8"))
            print(f"{path.relative_to(ROOT).as_posix():<24} written")
    print(f"Unicode {PINNED}: table sha256 {sha(t)}, {len(t)} characters")
    return 0 if ok or "--check" not in argv else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
