"""Generate the one Unicode table both diffgate ports read a Python name with (NOTE_path2_seventh_pass_2026_09_25),
and the set of code points the Pythons this package supports read differently from it (NOTE_path2_eighth_pass).

    py -3.12 web/gate/gen_xid.py            # writes the GENERATED block of styxx/_xid.py and of web/gate/diffgate.js
    py -3.12 web/gate/gen_xid.py --check    # recomputes both and compares both blocks; writes nothing
    py -3.12 web/gate/gen_xid.py --record-sources [--python "py -3.14"] [--perl perl]
                                            # re-derives web/gate/xid_versions.json from the tools named
    py -3.12 web/gate/gen_xid.py --check-sources [--python "py -3.14"] [--perl perl]
                                            # the same, compared with the committed file; writes nothing
    py -3.N  web/gate/gen_xid.py --dump-masks   # this Python's own masks, as the table encodes them

The table is read from ONE Unicode version, 15.0.0, the database CPython 3.12 carries, and this script
REFUSES to build it under any other (`unicodedata.unidata_version` must be PINNED): the whole point is that no
runtime's tables decide a name any more, so the generator's own runtime may not either.

For every code point, three bits (styxx/_xid.py's docstring says how they are written):

    1  chr(c).isidentifier()                 XID_Start, or `_` -- the opening character of an identifier
    2  ("a" + chr(c)).isidentifier()         XID_Continue -- every later character
    4  chr(c).isalnum() or chr(c) == "_"     Python's `\\w` for a str pattern (sre: Py_UNICODE_ISALNUM or `_`)

CPython builds `str.isidentifier` from DerivedCoreProperties.txt's XID_Start and XID_Continue and `\\w` from
its alpha/decimal/digit/numeric flags, so the three bits are those properties of Unicode 15.0.0 as that
Python reads them. Both blocks carry the version and the sha256 of the table's ASCII bytes; the test suite
checks that the two blocks are identical and, under a 15.0.0 Python, that this script reproduces them.

THE SKEW SET (NOTE_path2_eighth_pass_2026_09_27, Y-3). The package installs on every Python from 3.9
(`requires-python >=3.9`, no cap), and each reads identifiers by its own Unicode: 13.0.0 (3.9, 3.10), 14.0.0
(3.11), 15.0.0 (3.12), 15.1.0 (3.13), 16.0.0 (3.14). Where one of them gives a code point other bits than
the table does, a name holding it is not the same name on every Python, and the ports cannot say which one
the author's Python reads. SKEW is every such code point, written as a second run-length string (mask 1 in
the set, 0 outside it) in the same encoding, so both ports decode it with the table's own decoder. Its
sources, committed in web/gate/xid_versions.json and re-derived by --record-sources:

    16.0.0   the masks CPython 3.14 reads (`--dump-masks` under that Python): exact.
    15.1.0   no Python 3.13 on the generating machine. Every code point 15.1.0 reads differently from 15.0.0
             is one 16.0.0 reads differently too -- 15.1.0 assigned CJK Extension I and a few symbols and
             made U+200C, U+200D, U+30FB and U+FF65 continue an identifier, and 16.0.0 keeps each of those
             (identifier properties are never withdrawn) -- so 16.0.0's difference holds 15.1.0's. Checked
             for those named code points, not for the whole database.
    14.0.0   the table's masks where Unicode's Age property places the code point at or before 14.0, else 0
    13.0.0   (none): Perl's UCD, `\\p{Present_In=14.0}` / `\\p{Present_In=13.0}`. The assigned-then-changed
             case is covered by the margin below, not by a 13.0.0 or 14.0.0 database, which is not on this
             machine.
    margin   every code point whose general category, read as the three bits (L and Nl open; those, Nd, Mn,
             Mc and Pc continue; L and N are words), differs between Unicode 3.2.0 (`unicodedata.ucd_3_2_0`,
             in every CPython) and 15.0.0: 28 code points, each moved long before 13.0, kept so that a
             category move is never read on one version only.
"""
from __future__ import annotations

import hashlib
import json
import re
import shlex
import subprocess
import sys
import unicodedata
from pathlib import Path

PINNED = "15.0.0"
SKEW_VERSIONS = ("13.0.0", "14.0.0", "15.1.0", "16.0.0")
HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
PY_FILE = ROOT / "styxx" / "_xid.py"
JS_FILE = HERE / "diffgate.js"
SOURCES = HERE / "xid_versions.json"
BEGIN = "GENERATED by web/gate/gen_xid.py -- do not edit by hand"
END = "END GENERATED"
ENDS = "0123456789abcdefghijklmnopqrstu"      # a digit that ends a number
MORE = "vwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"      # a digit that does not
WIDTH = 96
# 15.1.0's own changes, named so the claim above is checked where it is made (Unicode 15.1.0 release notes:
# CJK Unified Ideographs Extension I, U+2EBF0..U+2EE5D; Other_ID_Continue gained U+200C, U+200D, U+30FB, U+FF65).
UNICODE_15_1_CHANGES = [0x200C, 0x200D, 0x30FB, 0xFF65] + list(range(0x2EBF0, 0x2EE5E))
PERL_PRESENT_IN = r"""
binmode STDOUT;
for my $v ("13.0", "14.0") {
    my $start = -1;
    for my $c (0 .. 0x110000) {
        my $in = ($c < 0x110000 && !($c >= 0xD800 && $c <= 0xDFFF)) ? (chr($c) =~ /\p{Present_In=$v}/ ? 1 : 0) : 0;
        if ($in && $start < 0) { $start = $c; }
        if (!$in && $start >= 0) { print "$v $start ", $c - 1, "\n"; $start = -1; }
    }
}
my $newest = "?";
for my $v ("13.0", "14.0", "15.0", "15.1", "16.0", "17.0") { $newest = $v if eval { "a" =~ /\p{Present_In=$v}/; 1 }; }
print "unicode $newest\n";
"""


def mask(c: int) -> int:
    ch = chr(c)
    return ((1 if ch.isidentifier() else 0) | (2 if ("a" + ch).isidentifier() else 0)
            | (4 if (ch.isalnum() or ch == "_") else 0))


def encode(value: int) -> str:
    out = ENDS[value % 31]
    value //= 31
    while value:
        out = MORE[value % 31] + out
        value //= 31
    return out


def runs_of(values) -> str:
    """A run-length string over every code point: each run one number, length * 8 + value."""
    runs: list = []
    for k in values:
        if runs and runs[-1][0] == k:
            runs[-1][1] += 1
        else:
            runs.append([k, 1])
    return "".join(encode(n * 8 + k) for k, n in runs)


def decode(table: str) -> list:
    """The per-code-point values of a run-length string (the inverse of `runs_of`)."""
    out: list = []
    value = 0
    for ch in table:
        k = MORE.find(ch)
        if k >= 0:
            value = value * 31 + k
            continue
        value = value * 31 + ENDS.index(ch)
        out.extend([value & 7] * (value >> 3))
        value = 0
    if len(out) != 0x110000:
        sys.exit(f"gen_xid: a run-length string covers {len(out):#x} code points, not 0x110000")
    return out


def this_pythons_masks() -> list:
    return [mask(c) for c in range(0x110000)]


def table() -> str:
    if unicodedata.unidata_version != PINNED:
        sys.exit(f"gen_xid: this Python reads Unicode {unicodedata.unidata_version}; the table is pinned to "
                 f"{PINNED} (run it with py -3.12)")
    return runs_of(this_pythons_masks())


def category_bits(cat: str) -> int:
    """The three bits a general category alone gives (the margin's reading)."""
    opens = cat[0] == "L" or cat == "Nl"
    cont = opens or cat in ("Nd", "Mn", "Mc", "Pc")
    return (1 if opens else 0) | (2 if cont else 0) | (4 if cat[0] in "LN" else 0)


def margin() -> set:
    old = unicodedata.ucd_3_2_0
    return {c for c in range(0x110000)
            if old.category(chr(c)) != "Cn"
            and category_bits(old.category(chr(c))) != category_bits(unicodedata.category(chr(c)))}


def skew(t15: list, sources: dict) -> list:
    """1 where some supported Python's Unicode gives a code point other bits than the table, else 0."""
    v = sources["versions"]
    m16 = decode(v["16.0.0"]["table"])
    present = {ver: decode(v[ver]["present_in"]) for ver in ("13.0.0", "14.0.0")}
    for c in UNICODE_15_1_CHANGES:
        if m16[c] == t15[c]:
            sys.exit(f"gen_xid: U+{c:04X} changed in 15.1.0 but 16.0.0 reads it as 15.0.0 does; "
                     "16.0.0's difference would not hold 15.1.0's")
    extra = margin()
    out = []
    for c in range(0x110000):
        differs = (m16[c] != t15[c]
                   or any((t15[c] if present[ver][c] else 0) != t15[c] for ver in present)
                   or c in extra)
        out.append(1 if differs else 0)
    return out


def sha(t: str) -> str:
    return hashlib.sha256(t.encode("ascii")).hexdigest()


def chunks(t: str) -> list:
    return [t[i:i + WIDTH] for i in range(0, len(t), WIDTH)]


def python_block(t: str, s: str) -> list:
    return ([f"# {BEGIN}", f'UNICODE_VERSION = "{PINNED}"', f'TABLE_SHA256 = "{sha(t)}"', "TABLE = ("]
            + [f'    "{c}"' for c in chunks(t)] + [")",
               f'SKEW_VERSIONS = "{" ".join(SKEW_VERSIONS)}"', f'SKEW_SHA256 = "{sha(s)}"', "SKEW = ("]
            + [f'    "{c}"' for c in chunks(s)] + [")", f"# {END}"])


def js_block(t: str, s: str) -> list:
    body, skew_body = chunks(t), chunks(s)
    return ([f"// {BEGIN}", f'const _XID_UNICODE_VERSION = "{PINNED}";', f'const _XID_TABLE_SHA256 = "{sha(t)}";',
             "const _XID_TABLE ="]
            + [f'  "{c}"' + (";" if i == len(body) - 1 else " +") for i, c in enumerate(body)]
            + [f'const _XID_SKEW_VERSIONS = "{" ".join(SKEW_VERSIONS)}";', f'const _XID_SKEW_SHA256 = "{sha(s)}";',
               "const _XID_SKEW ="]
            + [f'  "{c}"' + (";" if i == len(skew_body) - 1 else " +") for i, c in enumerate(skew_body)]
            + [f"// {END}"])


def splice(path: Path, block: list) -> tuple[str, str]:
    """(the file as it is, the file with its GENERATED block replaced), in the file's own line ending."""
    raw = path.read_bytes().decode("utf-8")
    nl = "\r\n" if "\r\n" in raw else "\n"
    lines = raw.split(nl)
    starts = [i for i, x in enumerate(lines) if x.rstrip().endswith(BEGIN)]
    ends = [i for i, x in enumerate(lines) if x.rstrip().endswith(END)]
    if len(starts) != 1 or len(ends) != 1 or ends[0] < starts[0]:
        sys.exit(f"gen_xid: {path} needs exactly one GENERATED block")
    new = lines[:starts[0]] + block + lines[ends[0] + 1:]
    return raw, nl.join(new)


def blocks_of(text: str) -> str:
    """The GENERATED block of a file's text, newlines normalised: what the test compares."""
    m = re.search(r"[^\n]*" + re.escape(BEGIN) + r".*?" + re.escape(END), text.replace("\r\n", "\n"), re.S)
    return m.group(0) if m else ""


def load_sources() -> dict:
    return json.loads(SOURCES.read_text(encoding="utf-8"))


def derive_sources(python_cmd: str, perl_cmd: str) -> dict:
    """xid_versions.json from the tools themselves: 16.0.0's masks from a Python that reads 16.0.0, and
    Unicode's Age for 13.0 and 14.0 from Perl's UCD."""
    r = subprocess.run(shlex.split(python_cmd) + [str(Path(__file__).resolve()), "--dump-masks"],
                       capture_output=True, text=True, timeout=600)
    if r.returncode != 0:
        sys.exit(f"gen_xid: {python_cmd} --dump-masks failed: {r.stderr[:300]}")
    version, py_version, encoded = r.stdout.split()
    if version != "16.0.0":
        sys.exit(f"gen_xid: {python_cmd} reads Unicode {version}, not 16.0.0")
    p = subprocess.run(shlex.split(perl_cmd) + ["-e", PERL_PRESENT_IN], capture_output=True, text=True,
                       timeout=600)
    if p.returncode != 0:
        sys.exit(f"gen_xid: {perl_cmd} failed: {p.stderr[:300]}")
    present = {"13.0": [0] * 0x110000, "14.0": [0] * 0x110000}
    perl_unicode = "?"
    for line in p.stdout.splitlines():
        parts = line.split()
        if parts[0] == "unicode":
            perl_unicode = parts[1]
            continue
        for c in range(int(parts[1]), int(parts[2]) + 1):
            present[parts[0]][c] = 1
    pv = subprocess.run(shlex.split(perl_cmd) + ["-e", "print $^V"], capture_output=True, text=True, timeout=60)
    age = (f"Unicode's Age property, from Perl {pv.stdout.strip()}'s UCD (\\p{{Present_In=...}}; its "
           f"database reads Unicode {perl_unicode})")
    return {
        "about": "The sources of the skew set (web/gate/gen_xid.py, NOTE_path2_eighth_pass_2026_09_27, Y-3). "
                 "Written by gen_xid.py --record-sources; read by gen_xid.py.",
        "table_version": PINNED,
        "versions": {
            "13.0.0": {"pythons": "3.9, 3.10", "source": f"the table's masks where {age} places the code point "
                                                           "at or before 13.0, else 0",
                       "present_in": runs_of(present["13.0"])},
            "14.0.0": {"pythons": "3.11", "source": f"the table's masks where {age} places the code point at or "
                                                     "before 14.0, else 0",
                       "present_in": runs_of(present["14.0"])},
            "15.1.0": {"pythons": "3.13", "source": "not installed where this was generated; held by 16.0.0's "
                                                     "difference (gen_xid.py's docstring)"},
            "16.0.0": {"pythons": "3.14", "source": f"CPython {py_version} unicodedata (str.isidentifier, "
                                                     "str.isalnum): gen_xid.py --dump-masks",
                       "table": encoded},
        },
    }


def main(argv: list) -> int:
    if "--dump-masks" in argv:
        print(unicodedata.unidata_version, sys.version.split()[0], runs_of(this_pythons_masks()))
        return 0
    if "--record-sources" in argv or "--check-sources" in argv:
        python_cmd = argv[argv.index("--python") + 1] if "--python" in argv else "py -3.14"
        perl_cmd = argv[argv.index("--perl") + 1] if "--perl" in argv else "perl"
        text = json.dumps(derive_sources(python_cmd, perl_cmd), indent=1) + "\n"
        if "--check-sources" in argv:
            same = SOURCES.exists() and SOURCES.read_bytes().decode("utf-8").replace("\r\n", "\n") == text
            print(f"web/gate/xid_versions.json {'matches' if same else 'DIFFERS'}")
            return 0 if same else 1
        SOURCES.write_bytes(text.encode("utf-8"))
        print("web/gate/xid_versions.json written")
        return 0
    t = table()
    s = runs_of(skew(decode(t), load_sources()))
    ok = True
    for path, block in ((PY_FILE, python_block(t, s)), (JS_FILE, js_block(t, s))):
        before, after = splice(path, block)
        same = before == after
        ok = ok and same
        if "--check" in argv:
            print(f"{path.relative_to(ROOT).as_posix():<24} {'matches' if same else 'DIFFERS'}")
        elif not same:
            path.write_bytes(after.encode("utf-8"))
            print(f"{path.relative_to(ROOT).as_posix():<24} written")
    print(f"Unicode {PINNED}: table sha256 {sha(t)}, {len(t)} characters; skew over {' '.join(SKEW_VERSIONS)}: "
          f"{sum(decode(s))} code points, sha256 {sha(s)}, {len(s)} characters")
    return 0 if ok or "--check" not in argv else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
