"""Regenerate THE LEDGER from committed receipts. Anyone can run this; nothing is hand-entered.

    python papers/build_ledger.py          # writes papers/LEDGER.md as UTF-8

Writes the file directly rather than to stdout: a shell redirect on Windows uses the console
codepage and silently mangles every non-ASCII character.
"""
import json, re, subprocess, sys
from pathlib import Path
from collections import Counter

ROOT = Path(__file__).resolve().parent
cy = [json.loads(l) for l in (ROOT / "autopilot" / "CYCLE_LOG.jsonl").read_text(encoding="utf-8").splitlines() if l.strip()]
seals = sorted(ROOT.rglob("*.seal.json"))
certs = sorted(p for p in ROOT.rglob("*.certificate.json") if "anc" not in p.parts)
preregs = sorted(ROOT.rglob("PREREG_*.md"))
NEG = r'INVALID__|NOT_|NO_|BLIND|WRONG|REFUS|_FAIL|DO NOT SHIP|RECALL|QUARANTIN|OVERTURN|INCOMPLETE'

seal_verdicts = Counter(json.loads(p.read_text(encoding="utf-8")).get("verdict") for p in seals)
cert_verdicts = Counter(json.loads(p.read_text(encoding="utf-8")).get("verdict") for p in certs)
negatives = [c for c in cy if re.search(NEG, c.get("verdict", ""))]
# The refusal classifier lives in its own module so it can be imported and TESTED by hand
# (tests/test_ledger_classifier.py). The regeneration guard in tests/test_ledger.py proves this
# file agrees with what it produces — never that the classification is right, which is how the
# refusal list came to print `SHIPPED`.
from ledger_verdicts import is_refusal as _is_refusal          # noqa: E402
from ledger_verdicts import refusal_tokens as _refusal_tokens  # noqa: E402

invalids = [c for c in cy if _is_refusal(c.get("verdict", ""))]
mention_only = [c for c in cy if "INVALID__" in (c.get("verdict") or "")
                and not _is_refusal(c.get("verdict", ""))]
gated = [p for p in preregs if "```gates" in p.read_text(encoding="utf-8")]
with_power = sum(1 for p in gated if '"power_basis"' in p.read_text(encoding="utf-8"))


def _first_commit(path):
    r = subprocess.run(["git", "log", "--diff-filter=A", "--format=%H", "--follow", "--",
                        path.name], cwd=path.parent, capture_output=True, text=True)
    h = [x for x in r.stdout.split() if x]
    return h[-1] if h else None


def _power_basis_split():
    """Gated preregs frozen AFTER ``power_basis`` existed, and how many declare one.

    Reporting ``with_power`` against every gated prereg understates the discipline: most were
    frozen before the field existed and a frozen prereg is never edited, so their denominator can
    never move. The honest ratio is over the ones that could have carried it.
    """
    r = subprocess.run(["git", "log", "--reverse", "--format=%H", "-S", "power_basis", "--",
                        "styxx/protocol.py"], cwd=ROOT.parent, capture_output=True, text=True)
    intro = next((x for x in r.stdout.split() if x), None)
    if intro is None:
        return None
    eligible = []
    for p in gated:
        add = _first_commit(p)
        if add and subprocess.run(["git", "merge-base", "--is-ancestor", intro, add],
                                  cwd=ROOT.parent, capture_output=True).returncode == 0:
            eligible.append(p)
    declaring = [p for p in eligible if '"power_basis"' in p.read_text(encoding="utf-8")]
    return len(declaring), len(eligible)


_split = _power_basis_split()

_LINES = []


def emit(s=""):
    _LINES.append(s)

emit("# THE LEDGER — every cycle this lab has run, and how many of them we lost")
emit()
emit("*Generated by `papers/build_ledger.py` from committed receipts. Nothing here is typed by")
emit("hand; re-run it and check.*")
emit()
emit("A research record is only worth what its negatives are worth. This file exists so that the")
emit("ratio is visible without reading 158 cycle entries.")
emit()
emit("## The count")
emit()
emit("| | |")
emit("|---|---|")
emit(f"| cycles logged | **{len(cy)}** |")
emit(f"| preregistrations frozen | **{len(preregs)}** ({len(gated)} carrying a machine-scored gates block) |")
emit(f"| OATH certificates | **{len(certs)}** |")
emit(f"| trust-stack seals | **{len(seals)}** |")
emit(f"| cycles ending in a refusal, null, retraction or INVALID | **{len(negatives)}** of {len(cy)} |")
emit(f"| verdicts that were literally `INVALID__*` — the machinery refusing its own run | **{len(invalids)}** |")
emit(f"| gates declaring a power basis | {with_power} of {len(gated)} gated preregs |")
if _split:
    emit(f"| — of those frozen *since* the field existed | **{_split[0]} of {_split[1]}** |")
emit()
emit("**The negatives row is not yet a measurement, and is published anyway.** The")
emit(f"{len(negatives)} is produced by matching a keyword list against each cycle's free-prose")
emit("verdict field, so a cycle counts as a loss whenever its commentary happens to contain one")
emit("of those words — the same defect that put `SHIPPED` in the refusal list below. Scoping the")
emit("identical keywords to the verdict's opening clause instead yields far fewer. Neither")
emit("number is right: the field is prose, and no keyword test over prose is a classifier. The")
emit("honest fix is a machine-readable verdict token per cycle, which is owed and not yet done.")
emit("The figure above is left standing rather than quietly restated because it has already been")
emit("cited in a frozen preregistration, which can never be edited; moving it here without")
emit("adjudicating all 163 cycles would replace a disclosed error with an undisclosed one.")
emit("Measured in `papers/ledger_classifier_audit.py`.")
emit()
if _split:
    emit("Both power-basis rows are reported because either alone misleads. A frozen")
    emit("preregistration is never edited, so the preregs written before `power_basis` existed can")
    emit("never acquire one and their denominator can never move; quoting only the first row")
    emit("understates the discipline, and quoting only the second hides how much of the corpus")
    emit("predates it.")
    emit()
emit("Certificate verdicts: " + ", ".join(f"`{k}` × {v}" for k, v in cert_verdicts.most_common()))
emit()
emit("Seal verdicts: " + ", ".join(f"`{k}` × {v}" for k, v in seal_verdicts.most_common()))
emit()
emit("## Every run the machinery refused")
emit()
emit("These are the cycles where a preregistered gate returned `INVALID__*` — the experiment was")
emit("run, the verdict was computed, and the frozen table said the result licenses nothing. Each")
emit("one cost real compute and produced no claim.")
emit()
for c in invalids:
    emit(f"- **cycle {c['cycle']}** ({c.get('date','?')}) — "
         f"{_refusal_tokens(c.get('verdict',''))}")
emit()
emit(f"A further **{len(mention_only)}** cycles mention an `INVALID__*` verdict in their own")
emit("commentary without having returned one, and are deliberately not listed here. Until")
emit("2026-08-26 they were, and the defect was visible in this file: the selection test was a")
emit("substring match over a free-prose verdict field, and the renderer printed only that")
emit("field's first word — so this section listed `SHIPPED`, `PRODUCT`, `DO`, `REWRITTEN` and")
emit("`BUILT` as runs the machinery refused, including the cycle that built this file, counted")
emit("as a loss because its verdict quotes this file's own negatives count. Measured in")
emit("`papers/ledger_classifier_audit.py`; the same mention-versus-use defect is documented in")
emit("the OATH verifier in `closed-model-frontier/RECON_oath_external_reach_2026_08_26.md`.")
emit()
emit("## The rule, measured")
emit()
emit("On 2026-08-06 this lab adopted a standing rule: *no instrument is announced before an")
emit("adversarial pass.* Three modules had shipped before it existed. The record since:")
emit()
emit("| | outcome |")
emit("|---|---|")
emit("| shipped before the rule | 3 modules, 3 broken within hours by red teams, 2 recalled the same day |")
emit("| shipped after the rule | released only once an adversary tried and failed |")
emit("| stopped by the rule | 2 modules quarantined pre-release, 0 users exposed |")
emit()
emit("The two quarantined modules are retained in the tree with their audit verdicts in their own")
emit("docstrings, because deleting a failed instrument hides the evidence.")
emit()
emit("## How to check any of this")
emit()
emit("```bash")
emit("python -m styxx.corpus_audit papers/      # re-certify every claim against its receipts")
emit("python papers/build_ledger.py             # regenerate this file")
emit("pytest -q                                 # the suite, including a whole-corpus re-score")
emit("```")
emit()
emit("The corpus audit re-runs the current verifier over every number this lab has ever published.")
emit("The test suite re-scores every committed result against its own frozen preregistration and")
emit("fails on a single changed verdict string.")
emit()
emit("## Why this file is not OATH-certified")
emit()
emit("Every other claim document here carries an OATH certificate binding its numbers to receipt")
emit("files. This one cannot: its numbers are *counts of the receipts themselves*, so there is no")
emit("receipt beneath them to bind to. It gets a stronger guarantee instead — **regeneration**. A")
emit("test in the suite rebuilds this file from the committed corpus and fails if a single")
emit("character differs, so it cannot drift from the record it describes and cannot be edited by")
emit("hand without the build going red.")
emit()
emit("*A lab that only publishes what worked is reporting a filtered sample of its own beliefs.*")


OUT = ROOT / "LEDGER.md"
OUT.write_text("\n".join(_LINES) + "\n", encoding="utf-8")
print(f"wrote {OUT} ({len(_LINES)} lines)")
