on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --locked
      - name: Tests
        run: |
          set -eo pipefail
          cargo test --locked
      - name: Docs
        run: cargo doc --no-deps
